"""The daily AI-written "pattern of the day" paragraph for the insights page.

One row per day, generated by the scheduled build-insight job (a single 70b
call over that day's aggregate statistics) -- stored so the page never spends
LLM budget on render, and yesterday's digest survives if today's job fails.
"""
from datetime import date

from sqlalchemy import Date, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.core.db import Base
from app.models.base import TimestampMixin, UUIDPrimaryKeyMixin


class InsightDigest(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "insight_digests"

    digest_date: Mapped[date] = mapped_column(Date, unique=True, index=True)
    body: Mapped[str] = mapped_column(Text)
    # "openai_compat" when a live model wrote it, "heuristic" for the
    # deterministic fallback template -- surfaced so the UI can label AI text.
    provider: Mapped[str] = mapped_column(String(30), default="heuristic")
