#!/usr/bin/env python3
"""Generate the frontend's copy of the taxonomy from app/taxonomy.py.

Why this exists: the category slugs, region slugs and risk types were written
out twice -- once in Python, once in TypeScript -- and kept in step by comments
asking the next person to remember. They drifted, and nothing noticed, because
nothing checked.

What is generated is the part the backend owns: slugs, the category/subcategory
tree, regions, risk types, and the Turkish labels for all of them. The labels
belong here because the backend already renders them -- into the newsletter, the
PDF and the recommendation prose -- so a second, hand-kept copy on the frontend
could only ever disagree with what the reader was emailed.

Tailwind classes and icons are not emitted and should not be: those are display
choices with no backend counterpart.

The frontend imports these as union types, so a slug that exists on one side
and not the other is a TypeScript error at build time rather than an empty
filter at runtime.

Usage:
    python -m scripts.export_taxonomy            # write the file
    python -m scripts.export_taxonomy --check    # exit 1 if it is stale (CI)
"""
import argparse
import sys
from pathlib import Path

# Run from backend/ either as a module or a script.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.taxonomy import (  # noqa: E402
    CATEGORIES,
    CATEGORY_LABELS_TR,
    COUNTRY_TO_REGION,
    GENERAL_CATEGORY,
    RISK_FAMILIES,
    RISK_SEVERITIES,
    REGION_LABELS_TR,
    RISK_TYPES,
    RIVAL_CODES,
)

OUTPUT = Path(__file__).resolve().parents[2] / "frontend" / "src" / "lib" / "taxonomy.gen.ts"

HEADER = """// Generated by backend/scripts/export_taxonomy.py -- do not edit by hand.
//
// Run `python -m scripts.export_taxonomy` from backend/ after changing
// app/taxonomy.py. CI fails when this file is out of date, so the two sides
// cannot drift apart silently the way they used to.
//
// Only structural truth lives here. Turkish category labels, colors and icons
// are frontend concerns and stay in taxonomy.ts.
"""


def _ts_string_union(name: str, values: list[str]) -> str:
    members = "\n".join(f"  | {value!r}".replace("'", '"') for value in values)
    return f"export type {name} =\n{members};\n"


def _ts_const_array(name: str, type_name: str, values: list[str]) -> str:
    items = ", ".join(f'"{value}"' for value in values)
    return f"export const {name}: readonly {type_name}[] = [{items}] as const;\n"


def render() -> str:
    category_slugs = [c.slug for c in CATEGORIES] + [GENERAL_CATEGORY]
    region_slugs = sorted(set(COUNTRY_TO_REGION.values()))

    parts: list[str] = [HEADER]

    parts.append(_ts_string_union("CategorySlug", category_slugs))
    parts.append(_ts_const_array("CATEGORY_SLUGS", "CategorySlug", category_slugs))
    parts.append("")

    parts.append("/** Turkish labels, owned by the backend -- the newsletter and PDF")
    parts.append(" *  render these same strings. */")
    parts.append("export const CATEGORY_LABELS_TR: Record<CategorySlug, string> = {")
    for slug in category_slugs:
        parts.append(f'  "{slug}": "{CATEGORY_LABELS_TR[slug]}",')
    parts.append("};\n")

    subcategory_slugs = sorted({s.slug for c in CATEGORIES for s in c.subcategories})
    parts.append(_ts_string_union("SubcategorySlug", subcategory_slugs))
    parts.append("")

    parts.append("/** Which subcategory slugs are legal under each category. */")
    parts.append("export const SUBCATEGORIES_BY_CATEGORY: Record<")
    parts.append("  CategorySlug,")
    parts.append("  readonly SubcategorySlug[]")
    parts.append("> = {")
    for category in CATEGORIES:
        items = ", ".join(f'"{s.slug}"' for s in category.subcategories)
        parts.append(f'  "{category.slug}": [{items}],')
    parts.append(f'  "{GENERAL_CATEGORY}": [],')
    parts.append("};\n")

    parts.append(_ts_string_union("RegionSlug", region_slugs))
    parts.append(_ts_const_array("REGION_SLUGS", "RegionSlug", region_slugs))
    parts.append("")

    parts.append("export const REGION_LABELS_TR: Record<RegionSlug, string> = {")
    for slug in region_slugs:
        parts.append(f'  "{slug}": "{REGION_LABELS_TR[slug]}",')
    parts.append("};\n")

    parts.append(_ts_string_union("RiskFamily", list(RISK_FAMILIES)))
    parts.append(_ts_string_union("RiskSeverity", list(RISK_SEVERITIES)))
    parts.append(_ts_string_union("RiskTypeSlug", [r.slug for r in RISK_TYPES]))
    parts.append("")

    parts.append("export interface RiskTypeDef {")
    parts.append("  slug: RiskTypeSlug;")
    parts.append("  family: RiskFamily;")
    parts.append("  /** Owned by the backend: the API returns these labels. */")
    parts.append("  labelTr: string;")
    parts.append("}\n")
    parts.append("export const RISK_TYPES: readonly RiskTypeDef[] = [")
    for risk in RISK_TYPES:
        parts.append(
            f'  {{ slug: "{risk.slug}", family: "{risk.family}", labelTr: "{risk.label_tr}" }},'
        )
    parts.append("] as const;\n")

    parts.append(_ts_string_union("RivalCode", list(RIVAL_CODES)))
    parts.append(_ts_const_array("RIVAL_CODES", "RivalCode", list(RIVAL_CODES)))

    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the generated file is missing or stale, without writing",
    )
    args = parser.parse_args()

    rendered = render()

    if args.check:
        if not OUTPUT.exists():
            print(f"{OUTPUT} does not exist -- run: python -m scripts.export_taxonomy")
            return 1
        if OUTPUT.read_text() != rendered:
            print(
                f"{OUTPUT} is stale -- app/taxonomy.py changed without regenerating it.\n"
                "Run: cd backend && python -m scripts.export_taxonomy"
            )
            return 1
        print(f"{OUTPUT.name} is up to date.")
        return 0

    OUTPUT.write_text(rendered)
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
