"""add kpi source_url and is_primary

Revision ID: 07904696aa02
Revises: 14398ef367b0
Create Date: 2026-07-13 21:48:21.316403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07904696aa02'
down_revision: Union[str, None] = '14398ef367b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpis', sa.Column('source_url', sa.String(length=500), nullable=True))
    # server_default backfills existing rows (all of which were the sole/primary
    # reading before cross-source verification existed) -- dropped after backfill
    # so future inserts must supply it explicitly via the ORM default.
    op.add_column(
        'kpis', sa.Column('is_primary', sa.Boolean(), nullable=False, server_default=sa.true())
    )
    op.alter_column('kpis', 'is_primary', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpis', 'is_primary')
    op.drop_column('kpis', 'source_url')
    # ### end Alembic commands ###
