"""drop unused simhash column

Revision ID: 106e812d6f26
Revises: 600aaa296512
Create Date: 2026-07-12 08:42:33.955611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '106e812d6f26'
down_revision: Union[str, None] = '600aaa296512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'simhash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('simhash', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
