"""add article search_vector

Revision ID: 14398ef367b0
Revises: 106e812d6f26
Create Date: 2026-07-12 08:53:23.386231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14398ef367b0'
down_revision: Union[str, None] = '106e812d6f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.create_index('ix_articles_search_vector', 'articles', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_articles_search_vector', table_name='articles', postgresql_using='gin')
    op.drop_column('articles', 'search_vector')
    # ### end Alembic commands ###
