"""add aviation_events and insight_digests tables

aviation_events: structured calendar entries behind the /events page --
events-as-articles keep serving the Gazete tab, but a month-grouped,
region-filterable calendar needs real start/end dates as columns, not dates
baked into a headline string.

insight_digests: one AI-written Turkish "pattern of the day" paragraph per day
for the /insights page, generated by the scheduled job so page renders never
spend LLM budget.

Revision ID: b31f7a9c1e02
Revises: adfccfca7f27
Create Date: 2026-07-17
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "b31f7a9c1e02"
down_revision = "adfccfca7f27"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "aviation_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(300), nullable=False),
        sa.Column("starts", sa.Date(), nullable=False),
        sa.Column("ends", sa.Date(), nullable=False),
        sa.Column("city", sa.String(120), nullable=False),
        sa.Column("country", sa.String(120), nullable=True),
        sa.Column("region", sa.String(30), nullable=True),
        sa.Column("url", sa.String(500), nullable=False, unique=True),
        sa.Column("summary_tr", sa.Text(), nullable=False, server_default=""),
        sa.Column("event_type", sa.String(20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.create_index("ix_aviation_events_starts", "aviation_events", ["starts"])
    op.create_index("ix_aviation_events_region", "aviation_events", ["region"])
    op.create_index("ix_aviation_events_event_type", "aviation_events", ["event_type"])

    op.create_table(
        "insight_digests",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("digest_date", sa.Date(), nullable=False, unique=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(30), nullable=False, server_default="heuristic"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.create_index("ix_insight_digests_digest_date", "insight_digests", ["digest_date"])


def downgrade() -> None:
    op.drop_table("insight_digests")
    op.drop_table("aviation_events")
