// GeoJSON feature name (src/lib/geo/world.json) -> world-region slug.
// Mirrors backend/app/taxonomy.py COUNTRY_TO_REGION's groupings (Turkey
// benchmarks with the Gulf carriers under middle-east, Russia under europe).
// Generated from the actual feature-name list; unmapped names (Antarctica,
// uninhabited territories) render neutral and are not clickable.
export const COUNTRY_REGION: Record<string, string> = {
  "Afghanistan": "asia",
  "Aland": "europe",
  "Albania": "europe",
  "Algeria": "africa",
  "American Samoa": "oceania",
  "Andorra": "europe",
  "Angola": "africa",
  "Antigua and Barb.": "central-america",
  "Argentina": "south-america",
  "Armenia": "asia",
  "Australia": "oceania",
  "Austria": "europe",
  "Azerbaijan": "asia",
  "Bahamas": "central-america",
  "Bahrain": "middle-east",
  "Bangladesh": "asia",
  "Barbados": "central-america",
  "Belarus": "europe",
  "Belgium": "europe",
  "Belize": "central-america",
  "Benin": "africa",
  "Bermuda": "north-america",
  "Bhutan": "asia",
  "Bolivia": "south-america",
  "Bosnia and Herz.": "europe",
  "Botswana": "africa",
  "Brazil": "south-america",
  "Brunei": "southeast-asia",
  "Bulgaria": "europe",
  "Burkina Faso": "africa",
  "Burundi": "africa",
  "Cambodia": "southeast-asia",
  "Cameroon": "africa",
  "Canada": "north-america",
  "Cape Verde": "africa",
  "Cayman Is.": "central-america",
  "Central African Rep.": "africa",
  "Chad": "africa",
  "Chile": "south-america",
  "China": "asia",
  "Colombia": "south-america",
  "Comoros": "africa",
  "Congo": "africa",
  "Costa Rica": "central-america",
  "Croatia": "europe",
  "Cuba": "central-america",
  "Curaçao": "central-america",
  "Cyprus": "europe",
  "Czech Rep.": "europe",
  "Côte d'Ivoire": "africa",
  "Dem. Rep. Congo": "africa",
  "Dem. Rep. Korea": "asia",
  "Denmark": "europe",
  "Djibouti": "africa",
  "Dominica": "central-america",
  "Dominican Rep.": "central-america",
  "Ecuador": "south-america",
  "Egypt": "africa",
  "El Salvador": "central-america",
  "Eq. Guinea": "africa",
  "Eritrea": "africa",
  "Estonia": "europe",
  "Ethiopia": "africa",
  "Faeroe Is.": "europe",
  "Falkland Is.": "south-america",
  "Fiji": "oceania",
  "Finland": "europe",
  "Fr. Polynesia": "oceania",
  "France": "europe",
  "Gabon": "africa",
  "Gambia": "africa",
  "Georgia": "asia",
  "Germany": "europe",
  "Ghana": "africa",
  "Greece": "europe",
  "Greenland": "north-america",
  "Grenada": "central-america",
  "Guam": "oceania",
  "Guatemala": "central-america",
  "Guinea": "africa",
  "Guinea-Bissau": "africa",
  "Guyana": "south-america",
  "Haiti": "central-america",
  "Honduras": "central-america",
  "Hungary": "europe",
  "Iceland": "europe",
  "India": "asia",
  "Indonesia": "southeast-asia",
  "Iran": "middle-east",
  "Iraq": "middle-east",
  "Ireland": "europe",
  "Isle of Man": "europe",
  "Israel": "middle-east",
  "Italy": "europe",
  "Jamaica": "central-america",
  "Japan": "asia",
  "Jersey": "europe",
  "Jordan": "middle-east",
  "Kazakhstan": "asia",
  "Kenya": "africa",
  "Kiribati": "oceania",
  "Korea": "asia",
  "Kuwait": "middle-east",
  "Kyrgyzstan": "asia",
  "Lao PDR": "southeast-asia",
  "Latvia": "europe",
  "Lebanon": "middle-east",
  "Lesotho": "africa",
  "Liberia": "africa",
  "Libya": "africa",
  "Liechtenstein": "europe",
  "Lithuania": "europe",
  "Luxembourg": "europe",
  "Macedonia": "europe",
  "Madagascar": "africa",
  "Malawi": "africa",
  "Malaysia": "southeast-asia",
  "Mali": "africa",
  "Malta": "europe",
  "Mauritania": "africa",
  "Mauritius": "africa",
  "Mexico": "central-america",
  "Micronesia": "oceania",
  "Moldova": "europe",
  "Mongolia": "asia",
  "Montenegro": "europe",
  "Montserrat": "central-america",
  "Morocco": "africa",
  "Mozambique": "africa",
  "Myanmar": "southeast-asia",
  "N. Cyprus": "middle-east",
  "N. Mariana Is.": "oceania",
  "Namibia": "africa",
  "Nepal": "asia",
  "Netherlands": "europe",
  "New Caledonia": "oceania",
  "New Zealand": "oceania",
  "Nicaragua": "central-america",
  "Niger": "africa",
  "Nigeria": "africa",
  "Niue": "oceania",
  "Norway": "europe",
  "Oman": "middle-east",
  "Pakistan": "asia",
  "Palau": "oceania",
  "Palestine": "middle-east",
  "Panama": "central-america",
  "Papua New Guinea": "oceania",
  "Paraguay": "south-america",
  "Peru": "south-america",
  "Philippines": "southeast-asia",
  "Poland": "europe",
  "Portugal": "europe",
  "Puerto Rico": "central-america",
  "Qatar": "middle-east",
  "Romania": "europe",
  "Russia": "europe",
  "Rwanda": "africa",
  "S. Geo. and S. Sandw. Is.": "africa",
  "S. Sudan": "africa",
  "Saint Lucia": "central-america",
  "Samoa": "oceania",
  "Saudi Arabia": "middle-east",
  "Senegal": "africa",
  "Serbia": "europe",
  "Seychelles": "africa",
  "Siachen Glacier": "asia",
  "Sierra Leone": "africa",
  "Singapore": "southeast-asia",
  "Slovakia": "europe",
  "Slovenia": "europe",
  "Solomon Is.": "oceania",
  "Somalia": "africa",
  "South Africa": "africa",
  "Spain": "europe",
  "Sri Lanka": "asia",
  "St. Pierre and Miquelon": "north-america",
  "St. Vin. and Gren.": "central-america",
  "Sudan": "africa",
  "Suriname": "south-america",
  "Swaziland": "africa",
  "Sweden": "europe",
  "Switzerland": "europe",
  "Syria": "middle-east",
  "São Tomé and Principe": "africa",
  "Tajikistan": "asia",
  "Tanzania": "africa",
  "Thailand": "southeast-asia",
  "Timor-Leste": "southeast-asia",
  "Togo": "africa",
  "Tonga": "oceania",
  "Trinidad and Tobago": "central-america",
  "Tunisia": "africa",
  "Turkey": "middle-east",
  "Turkmenistan": "asia",
  "Turks and Caicos Is.": "central-america",
  "U.S. Virgin Is.": "central-america",
  "Uganda": "africa",
  "Ukraine": "europe",
  "United Arab Emirates": "middle-east",
  "United Kingdom": "europe",
  "United States": "north-america",
  "Uruguay": "south-america",
  "Uzbekistan": "asia",
  "Vanuatu": "oceania",
  "Venezuela": "south-america",
  "Vietnam": "southeast-asia",
  "W. Sahara": "africa",
  "Yemen": "middle-east",
  "Zambia": "africa",
  "Zimbabwe": "africa",
};
