"""Canonical article taxonomy shared by the heuristic categorizer, the live LLM
prompts, the enrichment pipeline, and the /articles API.

This module is the single source of truth for slugs *and* for the Turkish
labels that go with them. The labels used to be retyped in four places -- the
recommendations service, the newsletter template, the newspaper page and the
frontend taxonomy -- and there was nothing to notice when one of them drifted.
The frontend receives the slugs and labels through
frontend/src/lib/taxonomy.gen.ts, generated by scripts/export_taxonomy.py; CI
fails when that file is stale. Colors and icons remain frontend concerns.
"""
from dataclasses import dataclass, field

from app.data import country_regions_by_name


@dataclass
class SubcategoryDef:
    slug: str
    keywords: list[str]


@dataclass
class CategoryDef:
    slug: str
    keywords: list[str]
    subcategories: list[SubcategoryDef] = field(default_factory=list)


# A note that every keyword list below depends on, and that cost three dead
# keywords before it was written down: the scorer matches against
# app.pipeline.hashing.normalize_text(text), which lowercases and then replaces
# every character outside [a-z0-9\s] with a space. So "add-on" in the article
# arrives as "add on", and the keyword "add-on" -- escaped into `\badd\-on\b` --
# could never match it. Hyphens, apostrophes and Turkish letters are all in that
# class: "gecikme" is matchable, "gecikmeler" is a different word, and
# "kapasitesi"/"artışı" arrive as "kapasitesi"/"art" respectively.
#
# Two rules follow. Write phrases the way normalize_text leaves them (spaces,
# never punctuation), and keep Turkish keywords to ASCII-only stems that stand
# alone as words. test_taxonomy_keywords.py enforces the first one.


# Order matters: this is also the default display/ranking order (Revenue
# Management first, per the RM-department focus of this portal).
CATEGORIES: list[CategoryDef] = [
    CategoryDef(
        slug="revenue_management",
        keywords=[
            "yield", "rask", "cask", "load factor", "fare", "fares", "pricing", "ancillary",
            "competitor", "capacity", "demand", "overbooking", "dynamic pricing",
            "ndc", "distribution", "revenue management", "unit revenue", "fare war",
            "price war", "airfare", "ticket price", "premium cabin", "business class",
            "booking", "bookings", "yield management", "capacity discipline", "seat sale",
            "revenue per", "load factors", "pricing power", "demand outlook", "rpk", "ask",
            "upsell", "bundling", "fare class", "revenue growth", "unbundling",
        ],
        # The desk's own nine beats, in reading order. Order is load-bearing:
        # subcategorize() keeps the first slug to reach the top score, so a
        # phrase that could plausibly belong to two of them is written into
        # exactly one -- "schedule change" is capacity (a schedule is where
        # capacity is expressed), not competitor, even though a rival's
        # schedule change is competitive news. Repeating it in both lists would
        # not make it reachable from the later one; it would only make the
        # tie-break, rather than the taxonomy, decide.
        subcategories=[
            SubcategoryDef(
                "competitor",
                [
                    "competitor", "competitors", "rival", "rivals", "undercut", "undercuts",
                    "market share", "competition", "compete", "vs ", "battle",
                    # The owner's RAKIP beat is wider than the word "rival": a
                    # carrier entering or leaving a market, or rebuilding a hub,
                    # is a competitive move whether or not the copy says so.
                    "market entry", "market exit", "new entrant", "enters the market",
                    "exits the market", "pulls out of", "hub strategy", "network strategy",
                    "network change", "head to head", "market leader", "gains share",
                    "loses share", "rakip", "rekabet",
                    # NOTE: rival airline NAMES deliberately do not live here.
                    # They were added in round 5 so rival stories would surface,
                    # but any article merely mentioning a carrier landed under
                    # "Rakip" -- an SR Technics engine-maintenance deal and an
                    # Embraer order both showed up there. Mentioning a carrier
                    # is an *entity* fact, and the Ana Rakipler filter
                    # (airline=RIVALS, app/repositories/article_repository.py)
                    # already answers it from the entity table. A subcategory
                    # should describe what the story is ABOUT.
                ],
            ),
            # NOTE: the old "region" subcategory is gone -- keyword matching
            # almost never assigned it (0 articles in production), and the
            # newspaper now has a real region filter driven by the entity-derived
            # enrichment.region field, which covers every category at once.
            SubcategoryDef(
                "pricing",
                [
                    "fare", "fares", "pricing", "price hike", "price cut", "price increase",
                    "dynamic pricing", "airfare", "airfares", "ticket price", "ticket prices",
                    "cheaper", "expensive", "fare war", "price war", "seat sale", "discount",
                    "fare increase", "fare cut", "raises fares", "cuts fares", "lowers fares",
                    "base fare", "surcharge", "fuel surcharge", "fare level", "fare structure",
                    "fiyat", "zam", "ucuz",
                ],
            ),
            SubcategoryDef(
                "promotion",
                # Compound phrases only: bare "sale"/"offer" match aircraft
                # sales and codeshare offers, which are not promotions.
                [
                    "promotion", "promo code", "promotional fare", "flash sale", "fare sale",
                    "seat sale", "special offer", "discount code", "black friday",
                    "cyber monday", "summer sale", "winter sale", "limited time offer",
                    "campaign fare", "promo fare", "kampanya", "indirim",
                ],
            ),
            # TALEP and KAPASİTE were one slug ("demand_capacity") and answered
            # two different questions with one word. A desk reading "bookings to
            # Europe up 12%" is looking at what the market wants; one reading
            # "third daily frequency on IST-LHR" is looking at what a carrier
            # supplies -- opposite sides of the same trade, and the one thing an
            # RM analyst most needs the newspaper to keep apart. Splitting them
            # is why this PR exists; the old combined slug is retired, not
            # aliased, and `python -m app.cli reclassify` re-files the history.
            SubcategoryDef(
                "demand",
                [
                    "demand", "demand trend", "demand trends", "booking trend", "booking trends",
                    "forward bookings", "advance bookings", "bookings", "booking momentum",
                    "passenger demand", "travel demand", "leisure travel", "business travel",
                    "corporate travel", "consumer behaviour", "consumer behavior",
                    "seasonal demand", "summer demand", "peak demand", "demand recovery",
                    "demand growth", "soft demand", "weak demand", "strong demand",
                    "pent up demand", "traffic growth", "talep",
                ],
            ),
            SubcategoryDef(
                "capacity",
                [
                    "capacity", "capacity increase", "capacity cut", "capacity growth",
                    "capacity reduction", "capacity discipline", "adds capacity",
                    "seat capacity", "available seat", "seats", "seat count", "frequency",
                    "frequencies", "frequency increase", "additional frequency",
                    "extra flights", "adds flights", "additional flights", "daily frequency",
                    "schedule change", "route suspension", "suspends route", "aircraft deployment",
                    "deploys", "redeploy", "overbooking", "kapasite", "ek sefer", "tarife",
                ],
            ),
            SubcategoryDef(
                "load_factor",
                [
                    "load factor", "load factors", "seat factor", "occupancy",
                    "occupancy rate", "passenger load factor", "plf", "doluluk",
                ],
            ),
            SubcategoryDef(
                "ancillary",
                [
                    "ancillary", "ancillary revenue", "ancillary income", "baggage fee",
                    "baggage fees", "seat selection", "seat fee", "paid seat", "extra legroom",
                    "priority boarding", "upsell", "bundling", "unbundling", "extra fee",
                    # "add on", not "add-on": see the normalize_text note above --
                    # the hyphenated spelling was unmatchable for as long as it
                    # was in this list.
                    "add on", "a la carte", "onboard sales", "loyalty revenue",
                    "ek gelir", "bagaj",
                ],
            ),
            SubcategoryDef(
                "distribution",
                [
                    "ndc", "distribution", "gds", "direct booking", "direct channel", "ota",
                    "travel agent", "travel agency", "booking channel", "distribution cost",
                    "offer and order", "one order", "airline retailing", "retailing", "api",
                    "amadeus", "sabre", "travelport", "metasearch", "dynamic offer", "acente",
                ],
            ),
            # FORECASTING is new: the desk plans against next season, and a
            # forecast revision was previously filed under demand alongside the
            # actuals it revises, which reads as if it had already happened.
            SubcategoryDef(
                "forecasting",
                [
                    "forecast", "forecasts", "forecasting", "forecast revision",
                    "demand forecast", "revenue forecast", "capacity forecast",
                    "traffic forecast", "industry forecast", "market outlook",
                    "demand outlook", "revenue outlook", "capacity outlook",
                    "industry outlook", "projection", "projections", "tahmin", "beklenti",
                ],
            ),
        ],
    ),
    CategoryDef(
        slug="fleet",
        # Deliberately excludes bare "aircraft", "engine", "cabin" and "jet":
        # they're near-stopwords in aviation copy and made fleet swallow ~40% of
        # everything. Model designations and fleet-specific phrases carry the
        # signal instead. ("grounding" lives in safety, where it belongs.)
        keywords=[
            "aircraft order", "aircraft delivery", "delivery", "deliveries", "boeing", "airbus",
            "fleet", "widebody", "narrowbody", "embraer", "bombardier", "a320", "a321", "a350",
            "a330", "a380", "737", "787", "777", "767", "dreamliner", "737 max",
            "retrofit", "lessor", "leasing", "jet order", "fleet plan", "e175", "e190",
            "aircraft purchase", "firm order", "fleet renewal", "retirement",
        ],
        subcategories=[
            SubcategoryDef(
                "order_delivery",
                ["order", "delivery", "purchase agreement", "firm order", "deliveries", "lease", "commitment"],
            ),
            SubcategoryDef(
                "maintenance",
                ["maintenance", "mro", "overhaul", "inspection", "retrofit", "engine issue", "repair", "check"],
            ),
        ],
    ),
    CategoryDef(
        slug="network",
        keywords=[
            "route", "nonstop", "launch flight", "service between", "network", "frequency",
            "new route", "direct flight", "connects", "schedule", "seasonal service",
            "routes", "flights between", "resume", "resumes", "hub", "codeshare",
            "destination", "expands to", "launches service", "adds flights", "drops route",
        ],
        subcategories=[
            SubcategoryDef(
                "new_route",
                ["launch", "new route", "new service", "nonstop", "adds flights", "expands to", "resumes", "debut"],
            ),
            SubcategoryDef(
                "cancellation",
                ["cancel", "suspend", "discontinue", "axed", "drops route", "cuts", "ends service", "exit"],
            ),
            SubcategoryDef(
                "seasonal",
                ["seasonal", "summer schedule", "winter schedule", "summer season", "peak season"],
            ),
        ],
    ),
    CategoryDef(
        slug="finance",
        keywords=[
            "revenue", "profit", "earnings", "stock", "shares", "ipo", "quarterly", "loss", "margin",
            "results", "financial", "guidance", "outlook", "investor", "dividend", "debt",
            "bankruptcy", "chapter 11", "merger", "acquisition", "stake", "valuation",
            "net income", "ebit", "q1", "q2", "q3", "q4", "full year", "billion", "profitability",
        ],
        subcategories=[
            SubcategoryDef(
                "results",
                ["earnings", "quarterly", "profit", "loss", "results", "net income", "ebit", "full year"],
            ),
            SubcategoryDef(
                "equity", ["stock", "shares", "ipo", "market cap", "investor", "dividend", "stake", "shareholder"]
            ),
        ],
    ),
    CategoryDef(
        slug="safety",
        keywords=[
            "crash", "incident", "emergency", "mayday", "diverted", "grounded", "investigation",
            "accident", "ntsb", "aaib", "turbulence", "near miss", "runway excursion",
            "evacuation", "smoke", "fire", "injured", "fatal", "safety", "malfunction",
            "emergency landing", "bird strike", "depressurisation", "depressurization",
        ],
    ),
    CategoryDef(
        slug="regulatory",
        keywords=[
            "faa", "easa", "icao", "regulation", "certification", "government", "ban",
            "regulator", "approval", "certified", "rule", "law", "policy", "sanction",
            "tariff", "airspace", "bilateral", "slot rules", "compensation rules", "eu261",
            "dot", "caa", "shgm", "authority", "directive", "airworthiness", "mandate",
        ],
    ),
    CategoryDef(
        slug="sustainability",
        keywords=[
            "saf", "sustainable aviation fuel", "emissions", "carbon", "net zero",
            "sustainability", "green", "climate", "corsia", "offset", "hydrogen",
            "electric aircraft", "biofuel", "decarbon", "environmental", "noise",
        ],
    ),
    CategoryDef(
        slug="airport",
        keywords=[
            "airport", "terminal", "runway", "expansion", "slot",
            "hub airport", "gate", "concourse", "apron", "baggage handling",
            "airport capacity", "new terminal", "airport opens", "ground handling",
            "security checkpoint", "customs", "passenger experience", "lounge",
        ],
        # Havalimanı had no subcategories at all, which was survivable while it
        # was one tab among six and is not now that it is one of the paper's
        # three sections: every airport story landed in one undifferentiated
        # pile, and a slot decision at LHR read the same as a lounge refurb.
        # These nine are the owner's beats, and between them they give every
        # keyword in the category list above somewhere specific to land.
        subcategories=[
            SubcategoryDef(
                "slot",
                [
                    "slot", "slots", "slot allocation", "slot coordination", "slot pair",
                    "slot swap", "slot waiver", "slot rules", "slot coordinator",
                    "level 3 airport", "use it or lose it",
                ],
            ),
            # Compound phrases only, deliberately: bare "capacity" is the single
            # most common word in an airport story and would have swallowed the
            # terminal, runway and congestion beats below. The Turkish stem is
            # the exception -- "kapasite" standing alone in Turkish copy really
            # is about capacity, and Turkish agglutination gives us no compound
            # that survives normalize_text.
            SubcategoryDef(
                "airport_capacity",
                [
                    "airport capacity", "capacity constraint", "capacity constraints",
                    "capacity crunch", "capacity cap", "capacity limit", "declared capacity",
                    "handling capacity", "annual capacity", "passenger capacity",
                    "capacity shortfall", "kapasite",
                ],
            ),
            SubcategoryDef(
                "terminal",
                [
                    "terminal", "new terminal", "terminal expansion", "terminal building",
                    "concourse", "pier", "boarding gate", "check in hall", "satellite terminal",
                    "yeni terminal",
                ],
            ),
            SubcategoryDef(
                "infrastructure",
                [
                    "runway", "new runway", "third runway", "second runway", "taxiway", "apron",
                    "stand", "infrastructure", "expansion project", "expansion plan",
                    "construction", "modernisation", "modernization", "refurbishment",
                    "master plan", "pist",
                ],
            ),
            SubcategoryDef(
                "disruption",
                [
                    "congestion", "congested", "disruption", "disruptions", "delays",
                    "closure", "closed", "shutdown", "outage", "power outage", "restriction",
                    "restrictions", "flight cap", "queues", "overcrowding", "bottleneck",
                    "gecikme", "aksama",
                ],
            ),
            SubcategoryDef(
                "traffic",
                [
                    "passenger traffic", "passenger numbers", "passengers handled",
                    "throughput", "record traffic", "traffic figures", "cargo traffic",
                    "cargo volume", "tonnage", "footfall", "kargo",
                ],
            ),
            SubcategoryDef(
                "new_service",
                [
                    "new route", "new routes", "new service", "new airline", "new carrier",
                    "airline entry", "starts flights", "launches flights", "adds airline",
                    "hub development", "new base", "base opening", "yeni hat",
                ],
            ),
            SubcategoryDef(
                "ground_handling",
                [
                    "ground handling", "handling agent", "baggage handling", "baggage system",
                    "de icing", "ramp", "turnaround", "pushback", "yer hizmetleri",
                ],
            ),
            SubcategoryDef(
                "passenger_experience",
                [
                    "passenger experience", "lounge", "security checkpoint", "customs",
                    "immigration", "e gate", "biometric", "fast track", "duty free",
                    "wayfinding", "pasaport",
                ],
            ),
        ],
    ),
    CategoryDef(
        slug="labor",
        keywords=[
            "union", "strike", "pilots", "contract negotiation", "staffing",
            "cabin crew", "flight attendant", "walkout", "industrial action", "pay deal",
            "labour", "labor", "workforce", "hiring", "layoff", "job cuts", "recruitment",
            "collective agreement", "shortage", "wage",
        ],
    ),
    CategoryDef(
        slug="events",
        keywords=[
            "conference", "summit", "air show", "airshow", "expo", "forum", "exhibition",
            "agm", "iata agm", "farnborough", "paris air show", "dubai airshow",
            "routes world", "world aviation festival", "aix", "apex", "mro europe",
            "trade show", "convention", "symposium", "congress", "aviation week event",
            "keynote", "delegates", "exhibitors", "singapore airshow",
        ],
        subcategories=[
            # "general" / "regional" aren't keyword-detected -- an events article
            # is "regional" whenever a region is detected via detect_region(),
            # otherwise it's "general". See app/llm/heuristic.py subcategorize().
            SubcategoryDef("general", []),
            SubcategoryDef("regional", []),
        ],
    ),
]

# --- the fleet/finance -> revenue_management shift rule ---------------------
#
# The owner's rule, stated as a rule rather than as a keyword: "Airline X orders
# 50 aircraft" is not on its own a story this desk publishes, but the same order
# *is* when it lands as serious added capacity in a market we sell -- then it is
# a capacity or a competitor story, and belongs under Gelir Yönetimi where the
# desk will actually see it.
#
# Deliberately narrow, and measured before it was written. Of 223 fleet/finance/
# general headlines sampled from production, 11 carried a strong RM signal and 8
# of those 11 were listicle clickbait -- so the real move rate is on the order of
# 1-3%. This is a correctness rule, not a way to refill three sections the paper
# just gave up; anything that reads it as a volume lever has misread it.
#
# Three things keep it narrow:
#   * it only ever fires on the two categories below -- a safety, labor or
#     regulatory story is never pulled into RM by a stray "new route";
#   * every phrase is a compound naming a concrete market effect. Bare "order",
#     "delivery", "profit" and "revenue" are absent by design: a plain order,
#     delivery or set of results is exactly what must NOT move;
#   * the evidence has to be loud (RM_SHIFT_MIN_SCORE), which at the scorer's
#     3x title weight means one hit in the headline or three in the body.
#
# Both classifiers apply it: app/llm/heuristic.py after keyword scoring, and the
# live models through the same rule spelled out in Turkish in
# app/llm/prompts.py categorize_prompt().
RM_SHIFT_FROM_CATEGORIES: tuple[str, ...] = ("fleet", "finance")

RM_SHIFT_KEYWORDS: list[str] = [
    # Capacity actually landing in a market.
    "capacity increase", "capacity boost", "capacity growth", "adds capacity",
    "add capacity", "boost capacity", "increase capacity", "expand capacity",
    "capacity expansion", "capacity cut", "cuts capacity", "capacity reduction",
    "seat capacity", "additional seats", "extra seats",
    # Network moves that change what is on sale.
    "new route", "new routes", "route launch", "launches route", "adds flights",
    "add flights", "additional flights", "extra flights", "additional frequency",
    "additional frequencies", "frequency increase", "daily frequency",
    "route suspension", "suspends route", "drops route",
    # Competitive and price effects.
    "market share", "market entry", "enters the market", "exits the market",
    "fare war", "price war", "undercut", "undercuts", "lower fares", "cut fares",
    "pricing power",
    # Turkish equivalents that survive normalize_text -- see the note at the top
    # of this module for why the list is this short.
    "ek sefer", "yeni hat", "kapasite",
]

#: One hit in the title (weighted 3x by the scorer), or three in the body.
RM_SHIFT_MIN_SCORE = 3

RM_SHIFT_TARGET = "revenue_management"


# The competitive set the product is scoped to: IATA code -> display name.
# Every carrier here owns a lane on the campaign timeline, a filter chip on the
# Gazete and Öneriler, and an entry in frontend/src/lib/nav.ts `airlineTabs`
# where its brand hex lives. A carrier outside this set has no lane to draw
# itself in, so a campaign by one is left as the article it already is.
#
# This lives here rather than next to the pipeline that reads it because it is
# the *frontend's* copy that used to drift: the set was written out in
# app/pipeline/promotions.py and again in nav.ts, kept in step by a test that
# hand-copied the literal. Singapore Airlines was added to the carrier master
# (app/ingest/carriers.py), started producing campaigns, and rendered on the
# Kampanyalar page as the bare string "SQ" in the default accent colour --
# because the hand-copied literal still said ten. It is now exported into
# taxonomy.gen.ts, so nav.ts fails the build when a carrier here has no brand
# entry, the same way an unnamed region already does.
TRACKED_AIRLINES: dict[str, str] = {
    "AF": "Air France",
    "BA": "British Airways",
    "EK": "Emirates",
    "EY": "Etihad Airways",
    "KL": "KLM",
    "LH": "Lufthansa",
    "QR": "Qatar Airways",
    "SQ": "Singapore Airlines",
    "PC": "Pegasus Airlines",
    "VF": "AJet",
    "TK": "Turkish Airlines",
}

# The user's named main rivals (IATA codes) -- powers the newspaper's
# "Ana Rakipler" filter (airline=RIVALS matches any of these). TK is the home
# carrier and deliberately not in this list, and neither is SQ: it is a carrier
# we scan and brand, not one of the rivals this desk was set up to watch.
RIVAL_CODES: tuple[str, ...] = ("AF", "BA", "EK", "EY", "KL", "LH", "PC", "QR", "VF")

# Editorial weighting: how much this portal cares about a category, on the same
# 0-1 scale as ArticleEnrichment.importance_score. Raw importance is
# `confidence * 0.7 + min(corroborating_count, 5) * 0.06`, so it measures how
# *well-attested* a story is, not how much an RM desk needs it -- a Boeing order
# carried by ten wires outscores a single-sourced competitor fare move every
# time. This bonus buys back the beats the portal exists for.
#
# Two consumers, deliberately one definition (app/services/edition_service.py
# ranks the daily edition's front page by importance + bonus; the Gazete's
# `min_importance` filter in app/repositories/article_repository.py applies the
# floor to the same weighted sum). They have to agree, and a second copy of
# these numbers would drift on the first tuning pass. Lives here because
# taxonomy.py is a leaf module -- it imports nothing from the app, so both the
# service and the repository layer can pull it in without a cycle.
FOCUS_BONUS: dict[str, float] = {
    "revenue_management": 0.30,
    "network": 0.18,
    "finance": 0.10,
    "events": 0.08,
}

# "general" is the fallback category: whatever scores zero against every
# category above lands here. It has no keyword list or subcategories of its own.
GENERAL_CATEGORY = "general"
CATEGORY_SLUGS: list[str] = [c.slug for c in CATEGORIES] + [GENERAL_CATEGORY]

# Turkish display labels. Canonical: the newsletter, the newspaper sections, the
# recommendation prose and the frontend all read these rather than keeping their
# own copy. test_taxonomy_labels.py asserts the coverage stays complete.
CATEGORY_LABELS_TR: dict[str, str] = {
    "revenue_management": "Gelir Yönetimi",
    "fleet": "Filo",
    "network": "Ağ & Rota",
    "finance": "Finans",
    "safety": "Emniyet",
    "regulatory": "Regülasyon",
    "sustainability": "Sürdürülebilirlik",
    "airport": "Havalimanı",
    "labor": "İşgücü",
    "events": "Etkinlik",
    "general": "Genel",
}

# Region slugs are produced by COUNTRY_TO_REGION below; these are their names.
REGION_LABELS_TR: dict[str, str] = {
    "europe": "Avrupa",
    "middle-east": "Orta Doğu",
    "africa": "Afrika",
    "north-america": "Kuzey Amerika",
    "south-america": "Güney Amerika",
    "central-america": "Orta Amerika",
    "asia": "Asya",
    "southeast-asia": "Güneydoğu Asya",
    "oceania": "Okyanusya",
}

CATEGORY_KEYWORDS: dict[str, list[str]] = {c.slug: c.keywords for c in CATEGORIES}
SUBCATEGORY_KEYWORDS: dict[str, dict[str, list[str]]] = {
    c.slug: {s.slug: s.keywords for s in c.subcategories} for c in CATEGORIES if c.subcategories
}

# Country (as extracted by the entity gazetteer, see app/llm/gazetteer.py) ->
# world region slug. Mirrors frontend/src/lib/nav.ts `worldRegions`. This is a
# practical approximation, not an authoritative geopolitical grouping --
# e.g. Turkey is grouped with Middle East here to match how airline
# revenue-management teams typically benchmark it against Gulf carriers. That
# same call is now made in exactly one place: app/hubs.py used to file IST and
# SAW under "europe" while this table filed Turkey under "middle-east", so the
# Hub Explorer and the newspaper's region filter disagreed about the home hub.
# hubs.py follows this table.
#
# These are the assignments the product made by hand, kept verbatim: full
# coverage is layered *underneath* them from the generated country table below,
# so widening coverage can never silently reclassify a country the product
# already had an opinion about.
CURATED_COUNTRY_REGION: dict[str, str] = {
    "united kingdom": "europe", "france": "europe", "germany": "europe",
    "spain": "europe", "italy": "europe", "netherlands": "europe",
    "russia": "europe", "greece": "europe", "portugal": "europe",
    "switzerland": "europe", "austria": "europe", "belgium": "europe",
    "poland": "europe", "sweden": "europe", "norway": "europe",
    "denmark": "europe", "finland": "europe", "ireland": "europe",
    "iceland": "europe",
    "turkey": "middle-east", "qatar": "middle-east", "united arab emirates": "middle-east",
    "saudi arabia": "middle-east", "israel": "middle-east",
    "egypt": "africa", "south africa": "africa", "nigeria": "africa",
    "kenya": "africa", "morocco": "africa",
    "united states": "north-america", "canada": "north-america",
    "mexico": "central-america", "panama": "central-america", "costa rica": "central-america",
    "brazil": "south-america", "argentina": "south-america", "chile": "south-america",
    "colombia": "south-america", "peru": "south-america", "ecuador": "south-america",
    "china": "asia", "japan": "asia", "south korea": "asia", "india": "asia",
    "indonesia": "southeast-asia", "thailand": "southeast-asia", "vietnam": "southeast-asia",
    "philippines": "southeast-asia", "singapore": "southeast-asia",
    "australia": "oceania", "new zealand": "oceania",
}

# The other ~200 countries, generated from the OurAirports country list by
# scripts/build_airports.py and cross-checked against
# frontend/src/lib/geo/region-countries.ts (the map's own country -> region
# table) so a signal cannot land in one region on the map and another in the
# ledger. The old 47-entry table was the reason "Riyadh-Malaga" and "Bergen"
# resolved to no region at all: the airport fallback in
# app/llm/heuristic.detect_region had nothing to look the country up in.
COUNTRY_TO_REGION: dict[str, str] = {
    **country_regions_by_name(),
    **CURATED_COUNTRY_REGION,
}

# ---------------------------------------------------------------------------
# Risk Radarı taxonomy
#
# A closed set of 9 event types in 2 families, classified out of the *existing*
# news feed by the enrichment pipeline -- there is no separate disaster data
# source. Deliberately closed: an open-ended "what kind of disaster is this"
# field would drift into dozens of near-synonyms across re-enrichment runs and
# make the country rollup uncountable. Anything that doesn't fit one of these
# nine is not a risk event as far as this product is concerned, and stays null.
#
# The frontend (frontend/src/components/risk-radar-client.tsx) mirrors these
# slugs with the same Turkish labels and its own icon per type -- keep both
# sides in sync when the taxonomy changes.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class RiskTypeDef:
    slug: str
    family: str  # natural | conflict
    label_tr: str


RISK_FAMILIES: tuple[str, ...] = ("natural", "conflict")

RISK_TYPES: list[RiskTypeDef] = [
    RiskTypeDef("earthquake", "natural", "Deprem"),
    RiskTypeDef("flood", "natural", "Sel"),
    RiskTypeDef("wildfire", "natural", "Yangın"),
    RiskTypeDef("volcano", "natural", "Volkanik"),
    RiskTypeDef("storm", "natural", "Fırtına"),
    RiskTypeDef("war", "conflict", "Savaş/Çatışma"),
    RiskTypeDef("coup", "conflict", "Darbe"),
    RiskTypeDef("attack", "conflict", "Saldırı"),
    RiskTypeDef("unrest", "conflict", "Toplumsal Gerginlik"),
]

RISK_TYPE_SLUGS: tuple[str, ...] = tuple(r.slug for r in RISK_TYPES)
RISK_TYPE_FAMILY: dict[str, str] = {r.slug: r.family for r in RISK_TYPES}
RISK_TYPE_LABELS_TR: dict[str, str] = {r.slug: r.label_tr for r in RISK_TYPES}

# Reuses the app's existing high|medium|low convention (event impact_level,
# recommendation priority) rather than inventing a fourth severity vocabulary.
RISK_SEVERITIES: tuple[str, ...] = ("high", "medium", "low")

# Weighted score behind the "Sıcak Noktalar" ranking. Computed server-side (see
# app/api/v1/risks.py) so the map, the ranking and the list all order countries
# by the same number instead of three client-side re-derivations of it.
RISK_SEVERITY_WEIGHT: dict[str, int] = {"high": 3, "medium": 2, "low": 1}


def is_valid_risk_type(slug: str | None) -> bool:
    """Closed-set gate. Everything that writes risk_type -- the LLM path, the
    heuristic, the CLI backfill -- goes through this, so a model inventing
    "tsunami" or "hurricane" writes null rather than a slug nothing can render.
    """
    return slug in RISK_TYPE_SLUGS


def risk_family_of(slug: str | None) -> str | None:
    return RISK_TYPE_FAMILY.get(slug) if slug else None


# ---------------------------------------------------------------------------
# Risk Radarı taxonomy — v2 (Faz 7)
#
# A second, independent taxonomy alongside the one above. Deliberately not a
# replacement in place: `RISK_TYPES` and `is_valid_risk_type` are still what
# app/llm/heuristic.py's classify_risk_heuristic (the only risk classifier
# actually running in production today) reads and writes, and that keyword
# matcher's patterns are built for natural-disaster/conflict granularity
# (earthquake vs. flood vs. wildfire). Repointing those constants to this
# taxonomy would silently change what the live Risk Radar shows before v2 has
# been compared against v1 for a single day. The pipeline v2 runner
# (app/agents/runner.py) and the consolidated classifier (app/llm/classify.py)
# import from here instead; v1 never sees this section.
#
# The reorganisation itself is the owner's: a revenue-management desk does not
# file "fuel price spike" and "earthquake" as siblings under a generic
# "disaster" umbrella. Eight families group risk by what kind of business
# decision it should trigger -- geopolitical and operational read close to the
# old natural/conflict split, but economic, fuel-cost, market-competitive,
# demand and infrastructure have no equivalent in the old scheme at all, and
# are exactly the categories a fare-and-network desk actually watches for.
#
# Two leaf types per family: specific enough to be different events, closed
# enough that the country/family rollups stay countable. A model inventing a
# type outside this set fails the call (see llm/classify.py) rather than
# writing a slug nothing can render.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class RiskCategoryDef:
    slug: str
    family: str
    label_tr: str


RISK_CATEGORY_FAMILIES: tuple[str, ...] = (
    "geopolitical", "operational", "regulatory", "economic",
    "fuel_cost", "market_competitive", "demand", "infrastructure",
)

RISK_CATEGORY_FAMILY_LABELS_TR: dict[str, str] = {
    "geopolitical": "Jeopolitik",
    "operational": "Operasyonel",
    "regulatory": "Düzenleyici",
    "economic": "Ekonomik",
    "fuel_cost": "Yakıt-Maliyet",
    "market_competitive": "Pazar-Rekabet",
    "demand": "Talep",
    "infrastructure": "Altyapı",
}

RISK_CATEGORIES: list[RiskCategoryDef] = [
    # Geopolitical -- war, unrest and attacks were three separate types before;
    # a revenue desk reacts to all three the same way (route suspension,
    # insurance, crew safety), so they are one type here. Sanctions are their
    # own because the reaction is different (payment/clearing risk, not
    # operational risk).
    RiskCategoryDef("conflict", "geopolitical", "Çatışma"),
    RiskCategoryDef("sanctions", "geopolitical", "Yaptırım"),
    # Operational -- an accident/incident (the old "storm" grounding a
    # weather-named fighter jet lived here by keyword accident; it no longer
    # can, since this taxonomy has no bare weather types to collide with) vs.
    # a disruption that stops flights without anyone being hurt (strike,
    # closure, ATC action affecting one carrier).
    RiskCategoryDef("accident_incident", "operational", "Kaza/Olay"),
    RiskCategoryDef("disruption", "operational", "Operasyonel Aksama"),
    # Regulatory
    RiskCategoryDef("restriction", "regulatory", "Kısıtlama/Yasak"),
    RiskCategoryDef("policy_change", "regulatory", "Mevzuat Değişikliği"),
    # Economic
    RiskCategoryDef("currency_crisis", "economic", "Kur Krizi"),
    RiskCategoryDef("macro_shock", "economic", "Makroekonomik Şok"),
    # Fuel / cost
    RiskCategoryDef("fuel_price_spike", "fuel_cost", "Yakıt Fiyat Artışı"),
    RiskCategoryDef("fuel_shortage", "fuel_cost", "Yakıt Kıtlığı"),
    # Market / competitive
    RiskCategoryDef("capacity_shift", "market_competitive", "Kapasite Değişimi"),
    RiskCategoryDef("price_war", "market_competitive", "Fiyat Savaşı"),
    # Demand
    RiskCategoryDef("demand_shock", "demand", "Talep Düşüşü"),
    RiskCategoryDef("demand_surge", "demand", "Talep Artışı"),
    # Infrastructure -- an airport-side problem (closure, damage, congestion)
    # vs. an airspace/ATC-side one (a country closing its airspace, a control
    # centre outage) are different mitigations (reroute a station vs. reroute
    # a flight path), so they stay separate types.
    RiskCategoryDef("airport_disruption", "infrastructure", "Havalimanı Aksaması"),
    RiskCategoryDef("atc_disruption", "infrastructure", "Hava Trafik Aksaması"),
]

RISK_CATEGORY_SLUGS: tuple[str, ...] = tuple(r.slug for r in RISK_CATEGORIES)
RISK_CATEGORY_FAMILY_OF: dict[str, str] = {r.slug: r.family for r in RISK_CATEGORIES}
RISK_CATEGORY_LABELS_TR: dict[str, str] = {r.slug: r.label_tr for r in RISK_CATEGORIES}


def is_valid_risk_category(slug: str | None) -> bool:
    return slug in RISK_CATEGORY_SLUGS


def risk_category_family_of(slug: str | None) -> str | None:
    return RISK_CATEGORY_FAMILY_OF.get(slug) if slug else None


# ---------------------------------------------------------------------------
# Kampanya İstihbaratı taxonomy
#
# Four independent closed sets, all of them string columns on `promotions`
# rather than Postgres enums -- the same call the rest of this file already
# makes, and for the same reason: adding a value to a Postgres enum is a
# migration, adding one here is a code change that the golden set and the
# generated frontend union both notice immediately.
#
# The four answer four genuinely different questions about one row, and the
# reason they are not collapsed into one field is that they disagree in
# practice. A row can be a FLASH_SALE (what kind of offer), an ACTIVE_CAMPAIGN
# (is this a fare campaign at all), NETWORK_WIDE (which markets), and EXPIRED
# (where is it in time) -- four answers, one campaign, and merging any pair of
# them loses information the analyst table has a column for.
#
# Note on the deliberate name collision: LOYALTY_PROMOTION is both a campaign
# *type* and a business *class*. They are not the same statement. As a type it
# says "this offer is about miles"; as a business class it says "this is not a
# fare campaign and must never be published as one". A miles-earning promo that
# also cuts fares is type LOYALTY_PROMOTION with class ACTIVE_CAMPAIGN, and a
# pure mileage-sale page is both. Keeping the word in both sets costs nothing
# (they are separate dicts) and renaming one of them to avoid the overlap would
# make both read worse.
# ---------------------------------------------------------------------------

#: What kind of offer this is. Closed at 27 values, OTHER last: an open-ended
#: "campaign type" field would drift into dozens of near-synonyms across
#: re-extraction runs and make the per-type rollup uncountable, exactly as the
#: risk taxonomy above found. A model answering outside this set writes OTHER
#: rather than a slug nothing can render or count.
CAMPAIGN_TYPES: tuple[str, ...] = (
    # Discount shape -- how the saving is expressed.
    "FARE_DISCOUNT",
    "PERCENT_DISCOUNT",
    "FIXED_FARE",
    # Urgency / booking-horizon shape.
    "FLASH_SALE",
    "EARLY_BOOKING",
    "LAST_MINUTE",
    # Itinerary shape.
    "ROUND_TRIP_PROMOTION",
    "ONE_WAY_PROMOTION",
    # Scope of the offer.
    "DESTINATION_PROMOTION",
    "SEASONAL_PROMOTION",
    "NEW_ROUTE_PROMOTION",
    # Calendar pegs. These are their own types rather than SEASONAL_PROMOTION
    # with a date, because a revenue desk plans against them by name a year
    # ahead and wants last year's Black Friday next to this year's.
    "BLACK_FRIDAY",
    "CYBER_MONDAY",
    "SUMMER_SALE",
    "WINTER_SALE",
    "RAMADAN_PROMOTION",
    "EID_PROMOTION",
    "NATIONAL_HOLIDAY",
    # Audience segments.
    "STUDENT_PROMOTION",
    "FAMILY_PROMOTION",
    "CORPORATE_PROMOTION",
    # Loyalty and ancillary. A campaign can legitimately be one of these AND a
    # fare campaign; whether it counts as one is the business_class question
    # below, not this one.
    "LOYALTY_PROMOTION",
    "MILES_PROMOTION",
    "BAGGAGE_PROMOTION",
    "ANCILLARY_PROMOTION",
    "PARTNER_PROMOTION",
    # The honest fallback.
    "OTHER",
)

#: Turkish display labels. Same discipline as CATEGORY_LABELS_TR: the analyst
#: table, the campaign drawer, the alert mail and the frontend all read these
#: instead of keeping their own copy, so a relabel happens once.
CAMPAIGN_TYPE_LABELS_TR: dict[str, str] = {
    "FARE_DISCOUNT": "Bilet İndirimi",
    "PERCENT_DISCOUNT": "Yüzde İndirim",
    "FIXED_FARE": "Sabit Fiyat",
    "FLASH_SALE": "Flaş İndirim",
    "EARLY_BOOKING": "Erken Rezervasyon",
    "LAST_MINUTE": "Son Dakika",
    "ROUND_TRIP_PROMOTION": "Gidiş-Dönüş Kampanyası",
    "ONE_WAY_PROMOTION": "Tek Yön Kampanyası",
    "DESTINATION_PROMOTION": "Destinasyon Kampanyası",
    "SEASONAL_PROMOTION": "Sezonluk Kampanya",
    "NEW_ROUTE_PROMOTION": "Yeni Hat Kampanyası",
    "BLACK_FRIDAY": "Black Friday",
    "CYBER_MONDAY": "Cyber Monday",
    "SUMMER_SALE": "Yaz İndirimi",
    "WINTER_SALE": "Kış İndirimi",
    "RAMADAN_PROMOTION": "Ramazan Kampanyası",
    "EID_PROMOTION": "Bayram Kampanyası",
    "NATIONAL_HOLIDAY": "Resmî Tatil Kampanyası",
    "STUDENT_PROMOTION": "Öğrenci Kampanyası",
    "FAMILY_PROMOTION": "Aile Kampanyası",
    "CORPORATE_PROMOTION": "Kurumsal Kampanya",
    "LOYALTY_PROMOTION": "Sadakat Programı Kampanyası",
    "MILES_PROMOTION": "Mil Kampanyası",
    "BAGGAGE_PROMOTION": "Bagaj Kampanyası",
    "ANCILLARY_PROMOTION": "Ek Hizmet Kampanyası",
    "PARTNER_PROMOTION": "İş Birliği Kampanyası",
    "OTHER": "Diğer",
}

#: Is this even a fare campaign? The single most load-bearing field in the
#: whole campaign surface, and the reason it exists: of 131 rows the old
#: pipeline published, 129 were loyalty-programme guides, product promos,
#: credit-card content or plain news wearing a campaign's shape. Everything
#: except ACTIVE/UPCOMING/EXPIRED_CAMPAIGN is a row that must never reach the
#: published campaign timeline, however confidently it was extracted.
#:
#: The ACTIVE/UPCOMING/EXPIRED split is *derived from dates*, not detected
#: separately -- see CAMPAIGN_STATUSES and services/campaign_status.py. The
#: detection layer (agents/campaign_airline.py) only ever answers the "is this
#: a fare campaign" half.
CAMPAIGN_BUSINESS_CLASSES: tuple[str, ...] = (
    "ACTIVE_CAMPAIGN",
    "UPCOMING_CAMPAIGN",
    "EXPIRED_CAMPAIGN",
    "EVERGREEN_OFFER",
    "NEWS_ONLY",
    "PRODUCT_PROMOTION",
    "LOYALTY_PROMOTION",
)

CAMPAIGN_BUSINESS_CLASS_LABELS_TR: dict[str, str] = {
    "ACTIVE_CAMPAIGN": "Aktif Kampanya",
    "UPCOMING_CAMPAIGN": "Yaklaşan Kampanya",
    "EXPIRED_CAMPAIGN": "Süresi Dolmuş Kampanya",
    "EVERGREEN_OFFER": "Sürekli Teklif",
    "NEWS_ONLY": "Sadece Haber",
    "PRODUCT_PROMOTION": "Ürün/Hizmet Kampanyası",
    "LOYALTY_PROMOTION": "Sadakat Kampanyası",
}

#: How precisely the campaign's market is known, coarsest question first: an
#: OND ("IST-LHR") is a directional airport pair, a CITY_PAIR is the same
#: without committing to which airport, and REGION/NETWORK_WIDE are the honest
#: answers when the copy says "Avrupa'ya" or "tüm hatlarda". The ladder exists
#: so a regional campaign is never fanned out into invented OND pairs -- the
#: single most tempting and most wrong enrichment available here.
ROUTE_SCOPES: tuple[str, ...] = (
    "OND",
    "CITY_PAIR",
    "COUNTRY",
    "REGION",
    "NETWORK_WIDE",
)

ROUTE_SCOPE_LABELS_TR: dict[str, str] = {
    "OND": "Kalkış-Varış (OND)",
    "CITY_PAIR": "Şehir Çifti",
    "COUNTRY": "Ülke",
    "REGION": "Bölge",
    "NETWORK_WIDE": "Tüm Ağ",
}

#: Where the campaign is in time. Never stored -- computed at read time from
#: (dates, today) by services/campaign_status.py, which is why these slugs live
#: here rather than as a column's check constraint. See that module for the
#: decision table and for why storing this would be wrong.
CAMPAIGN_STATUSES: tuple[str, ...] = (
    "UPCOMING",
    "ACTIVE_BOOKING",
    "BOOKING_CLOSED_TRAVEL_ACTIVE",
    "EXPIRED",
    "UNKNOWN",
)

CAMPAIGN_STATUS_LABELS_TR: dict[str, str] = {
    "UPCOMING": "Yakında",
    "ACTIVE_BOOKING": "Satışta",
    "BOOKING_CLOSED_TRAVEL_ACTIVE": "Satış kapandı, seyahat sürüyor",
    "EXPIRED": "Süresi doldu",
    "UNKNOWN": "Belirsiz",
}


def is_valid_campaign_type(slug: str | None) -> bool:
    """Closed-set gate, same contract as is_valid_risk_type above: every write
    path goes through this, so a model inventing "MEGA_SALE" writes OTHER or
    null rather than a slug nothing can render, filter or count."""
    return slug in CAMPAIGN_TYPES


def is_valid_business_class(slug: str | None) -> bool:
    return slug in CAMPAIGN_BUSINESS_CLASSES


def is_valid_route_scope(slug: str | None) -> bool:
    return slug in ROUTE_SCOPES


def is_valid_campaign_status(slug: str | None) -> bool:
    return slug in CAMPAIGN_STATUSES


# ---------------------------------------------------------------------------
# Kampanya vs Promosyon
#
# The owner's fifth question about a row, and the one the other four could not
# answer: is this a *price* move or a *mechanism*? A revenue desk reacts to the
# first (a competitor cut fares to London by 40%) and files the second (a
# competitor is giving students a standing code). Both are worth publishing;
# reading them off one list as if they were the same kind of event is what
# makes the campaign page hard to scan.
#
# Why this is a derived mapping and not a sixth detected field: `campaign_type`
# already carries the answer. FLASH_SALE is a price move by definition and
# STUDENT_PROMOTION is an audience mechanism by definition, so asking a model
# (or a rulepack) to decide the kind a second time can only introduce a way for
# the two answers to disagree. The table below is therefore the single source
# and `campaign_kind_for()` the single reader -- the column on `promotions`
# exists so the analyst list can filter on it in SQL without re-deriving 27
# cases per query, and it is written from this table on every write path.
#
# The one type that is deliberately unmapped is OTHER. "We could not name this
# offer" is not evidence that it is a fare move or that it is a mechanism, and
# guessing either would put a row in a bucket nothing checked. OTHER rows come
# out with campaign_kind NULL, which the UI renders as "—" exactly like an
# unclassified legacy row.
# ---------------------------------------------------------------------------

CAMPAIGN_KINDS: tuple[str, ...] = ("CAMPAIGN", "PROMOTION")

CAMPAIGN_KIND_LABELS_TR: dict[str, str] = {
    "CAMPAIGN": "Kampanya (fiyat)",
    "PROMOTION": "Promosyon (mekanizma)",
}

#: campaign_type -> kind. Every value of CAMPAIGN_TYPES except OTHER appears
#: exactly once; the test suite asserts that exhaustiveness, so adding a type
#: without deciding its kind fails there rather than silently defaulting.
CAMPAIGN_TYPE_TO_KIND: dict[str, str] = {
    # --- CAMPAIGN: the offer is a price. -----------------------------------
    # The saving is expressed as money off a fare, so the thing that changed is
    # the fare itself.
    "FARE_DISCOUNT": "CAMPAIGN",
    "PERCENT_DISCOUNT": "CAMPAIGN",
    "FIXED_FARE": "CAMPAIGN",
    # Urgency and booking horizon: still a price, sold against a clock.
    "FLASH_SALE": "CAMPAIGN",
    "EARLY_BOOKING": "CAMPAIGN",
    "LAST_MINUTE": "CAMPAIGN",
    # Itinerary shape: a round-trip promotion is a round-trip *fare*.
    "ROUND_TRIP_PROMOTION": "CAMPAIGN",
    "ONE_WAY_PROMOTION": "CAMPAIGN",
    # Calendar pegs. A seasonal or holiday sale is a price move with a date on
    # it -- the peg says when, not what. SEASONAL_PROMOTION sits here for the
    # same reason SUMMER_SALE does, and splitting them would put two spellings
    # of one thing in two buckets.
    "SEASONAL_PROMOTION": "CAMPAIGN",
    "BLACK_FRIDAY": "CAMPAIGN",
    "CYBER_MONDAY": "CAMPAIGN",
    "SUMMER_SALE": "CAMPAIGN",
    "WINTER_SALE": "CAMPAIGN",
    "RAMADAN_PROMOTION": "CAMPAIGN",
    "EID_PROMOTION": "CAMPAIGN",
    "NATIONAL_HOLIDAY": "CAMPAIGN",
    # --- PROMOTION: the offer is a mechanism, a channel or an audience. -----
    # Who may take it up, rather than what it costs.
    "STUDENT_PROMOTION": "PROMOTION",
    "FAMILY_PROMOTION": "PROMOTION",
    "CORPORATE_PROMOTION": "PROMOTION",
    # Whose programme or partner it runs through.
    "PARTNER_PROMOTION": "PROMOTION",
    "LOYALTY_PROMOTION": "PROMOTION",
    "MILES_PROMOTION": "PROMOTION",
    # What is being given away alongside the seat.
    "ANCILLARY_PROMOTION": "PROMOTION",
    "BAGGAGE_PROMOTION": "PROMOTION",
    # Where it points. A destination or new-route push is a marketing
    # mechanism aimed at a market -- it may or may not carry a fare cut, and
    # when it does the extractor types it as a discount instead.
    "DESTINATION_PROMOTION": "PROMOTION",
    "NEW_ROUTE_PROMOTION": "PROMOTION",
}

# A code you have to enter and a channel you have to buy through are also
# mechanisms, and the owner's rule names both. Neither is a `campaign_type` --
# they live in `attrs_json` -- so they cannot sit in the table above. They are
# read as a fallback only, where the type said nothing (OTHER or null): a
# FLASH_SALE with a promo code is still a price move, while a nameless offer
# that exists only because you typed a code is not.
def campaign_kind_for(
    campaign_type: str | None,
    *,
    promo_code: str | None = None,
    sales_channel: str | None = None,
) -> str | None:
    """CAMPAIGN | PROMOTION | None, from the type and (only as a fallback) the
    mechanism.

    None means "not decidable", which is the honest answer for an unclassified
    legacy row and for OTHER. Callers write it through unchanged rather than
    substituting a default -- see the column docstring on models/promotion.py.
    """
    kind = CAMPAIGN_TYPE_TO_KIND.get(campaign_type or "")
    if kind is not None:
        return kind
    if promo_code or sales_channel:
        return "PROMOTION"
    return None


def is_valid_campaign_kind(slug: str | None) -> bool:
    return slug in CAMPAIGN_KINDS


# --- Source tiers ---------------------------------------------------------
#
# The owner's source-priority ladder, most authoritative first. Declared per
# source (models/source.py `tier`, seeded by ingest/sources_seed.py) and used
# by pipeline/confidence.py to weight a claim, by pipeline/clustering.py to
# pick a cluster's primary telling, and now by the Gazete to badge a card and
# filter a list.
#
# Lives here for the same reason FOCUS_BONUS does: taxonomy.py imports nothing
# from the app, so the schema layer, the repository layer and the pipeline can
# all read one definition without a cycle.
SOURCE_TIERS: tuple[str, ...] = ("official", "regulator", "agency", "trade", "aggregator")

#: Fallback for a source with no declared tier: bucket its bare trust_weight.
#: Every source ingest/sources_seed.py seeds declares a real tier, so this only
#: fires for a row seeded before that column existed and not yet reconciled, or
#: a source added by hand outside the seed list.
#:
#: Note what it cannot produce: "official". Being an airline's or a regulator's
#: own newsroom is a fact about who publishes the feed, not something a
#: confidence weight can be read backwards into -- so an undeclared source is
#: never promoted to the top rung by arithmetic.
TRUST_WEIGHT_TIERS: tuple[tuple[float, str], ...] = (
    (0.90, "regulator"),
    (0.75, "agency"),
    (0.50, "trade"),
)
DEFAULT_UNDECLARED_TIER = "aggregator"


def effective_source_tier(tier: str | None, trust_weight: float | None) -> str:
    """The tier a source counts as: the declared one, or its trust bucket.

    One definition with two callers that must never disagree --
    pipeline/clustering.py `tier_for_source` badges the Risk Radarı's
    publication chronology with it, and schemas/article.py puts it on every
    article card. A card reading "Ajans" while the same outlet reads
    "Düzenleyici" three pages over is the failure this prevents.
    """
    if tier:
        return tier
    weight = trust_weight if trust_weight is not None else 0.0
    for floor, name in TRUST_WEIGHT_TIERS:
        if weight >= floor:
            return name
    return DEFAULT_UNDECLARED_TIER
