"""Canonical article taxonomy shared by the heuristic categorizer, the live LLM
prompts, the enrichment pipeline, and the /articles API.

This module is the single source of truth for slugs *and* for the Turkish
labels that go with them. The labels used to be retyped in four places -- the
recommendations service, the newsletter template, the newspaper page and the
frontend taxonomy -- and there was nothing to notice when one of them drifted.
The frontend receives the slugs and labels through
frontend/src/lib/taxonomy.gen.ts, generated by scripts/export_taxonomy.py; CI
fails when that file is stale. Colors and icons remain frontend concerns.
"""
from dataclasses import dataclass, field

from app.data import country_regions_by_name


@dataclass
class SubcategoryDef:
    slug: str
    keywords: list[str]


@dataclass
class CategoryDef:
    slug: str
    keywords: list[str]
    subcategories: list[SubcategoryDef] = field(default_factory=list)


# Order matters: this is also the default display/ranking order (Revenue
# Management first, per the RM-department focus of this portal).
CATEGORIES: list[CategoryDef] = [
    CategoryDef(
        slug="revenue_management",
        keywords=[
            "yield", "rask", "cask", "load factor", "fare", "fares", "pricing", "ancillary",
            "competitor", "capacity", "demand", "overbooking", "dynamic pricing",
            "ndc", "distribution", "revenue management", "unit revenue", "fare war",
            "price war", "airfare", "ticket price", "premium cabin", "business class",
            "booking", "bookings", "yield management", "capacity discipline", "seat sale",
            "revenue per", "load factors", "pricing power", "demand outlook", "rpk", "ask",
            "upsell", "bundling", "fare class", "revenue growth", "unbundling",
        ],
        subcategories=[
            SubcategoryDef(
                "competitor",
                [
                    "competitor", "rival", "undercut", "market share", "competition",
                    "compete", "vs ", "battle",
                    # NOTE: rival airline NAMES deliberately do not live here.
                    # They were added in round 5 so rival stories would surface,
                    # but any article merely mentioning a carrier landed under
                    # "Rakip" -- an SR Technics engine-maintenance deal and an
                    # Embraer order both showed up there. Mentioning a carrier
                    # is an *entity* fact, and the Ana Rakipler filter
                    # (airline=RIVALS, app/repositories/article_repository.py)
                    # already answers it from the entity table. A subcategory
                    # should describe what the story is ABOUT.
                ],
            ),
            # NOTE: the old "region" subcategory is gone -- keyword matching
            # almost never assigned it (0 articles in production), and the
            # newspaper now has a real region filter driven by the entity-derived
            # enrichment.region field, which covers every category at once.
            SubcategoryDef(
                "pricing",
                [
                    "fare", "pricing", "price hike", "price cut", "dynamic pricing", "airfare",
                    "ticket price", "cheaper", "expensive", "fare war", "seat sale", "discount",
                ],
            ),
            SubcategoryDef(
                "promotion",
                # Compound phrases only: bare "sale"/"offer" match aircraft
                # sales and codeshare offers, which are not promotions.
                [
                    "promotion", "promo code", "promotional fare", "flash sale", "fare sale",
                    "seat sale", "special offer", "discount code", "black friday",
                    "kampanya", "indirim",
                ],
            ),
            SubcategoryDef(
                "demand_capacity",
                ["demand", "capacity", "overbooking", "forecast", "bookings", "traffic growth", "seats"],
            ),
            SubcategoryDef("load_factor", ["load factor", "seat factor", "occupancy", "load factors"]),
            SubcategoryDef(
                "ancillary",
                ["ancillary", "baggage fee", "seat selection", "upsell", "bundling", "extra fee", "add-on"],
            ),
            SubcategoryDef(
                "distribution",
                ["ndc", "distribution", "gds", "direct booking", "ota", "travel agent", "booking channel"],
            ),
        ],
    ),
    CategoryDef(
        slug="fleet",
        # Deliberately excludes bare "aircraft", "engine", "cabin" and "jet":
        # they're near-stopwords in aviation copy and made fleet swallow ~40% of
        # everything. Model designations and fleet-specific phrases carry the
        # signal instead. ("grounding" lives in safety, where it belongs.)
        keywords=[
            "aircraft order", "aircraft delivery", "delivery", "deliveries", "boeing", "airbus",
            "fleet", "widebody", "narrowbody", "embraer", "bombardier", "a320", "a321", "a350",
            "a330", "a380", "737", "787", "777", "767", "dreamliner", "737 max",
            "retrofit", "lessor", "leasing", "jet order", "fleet plan", "e175", "e190",
            "aircraft purchase", "firm order", "fleet renewal", "retirement",
        ],
        subcategories=[
            SubcategoryDef(
                "order_delivery",
                ["order", "delivery", "purchase agreement", "firm order", "deliveries", "lease", "commitment"],
            ),
            SubcategoryDef(
                "maintenance",
                ["maintenance", "mro", "overhaul", "inspection", "retrofit", "engine issue", "repair", "check"],
            ),
        ],
    ),
    CategoryDef(
        slug="network",
        keywords=[
            "route", "nonstop", "launch flight", "service between", "network", "frequency",
            "new route", "direct flight", "connects", "schedule", "seasonal service",
            "routes", "flights between", "resume", "resumes", "hub", "codeshare",
            "destination", "expands to", "launches service", "adds flights", "drops route",
        ],
        subcategories=[
            SubcategoryDef(
                "new_route",
                ["launch", "new route", "new service", "nonstop", "adds flights", "expands to", "resumes", "debut"],
            ),
            SubcategoryDef(
                "cancellation",
                ["cancel", "suspend", "discontinue", "axed", "drops route", "cuts", "ends service", "exit"],
            ),
            SubcategoryDef(
                "seasonal",
                ["seasonal", "summer schedule", "winter schedule", "summer season", "peak season"],
            ),
        ],
    ),
    CategoryDef(
        slug="finance",
        keywords=[
            "revenue", "profit", "earnings", "stock", "shares", "ipo", "quarterly", "loss", "margin",
            "results", "financial", "guidance", "outlook", "investor", "dividend", "debt",
            "bankruptcy", "chapter 11", "merger", "acquisition", "stake", "valuation",
            "net income", "ebit", "q1", "q2", "q3", "q4", "full-year", "billion", "profitability",
        ],
        subcategories=[
            SubcategoryDef(
                "results",
                ["earnings", "quarterly", "profit", "loss", "results", "net income", "ebit", "full-year"],
            ),
            SubcategoryDef(
                "equity", ["stock", "shares", "ipo", "market cap", "investor", "dividend", "stake", "shareholder"]
            ),
        ],
    ),
    CategoryDef(
        slug="safety",
        keywords=[
            "crash", "incident", "emergency", "mayday", "diverted", "grounded", "investigation",
            "accident", "ntsb", "aaib", "turbulence", "near miss", "runway excursion",
            "evacuation", "smoke", "fire", "injured", "fatal", "safety", "malfunction",
            "emergency landing", "bird strike", "depressurisation", "depressurization",
        ],
    ),
    CategoryDef(
        slug="regulatory",
        keywords=[
            "faa", "easa", "icao", "regulation", "certification", "government", "ban",
            "regulator", "approval", "certified", "rule", "law", "policy", "sanction",
            "tariff", "airspace", "bilateral", "slot rules", "compensation rules", "eu261",
            "dot", "caa", "shgm", "authority", "directive", "airworthiness", "mandate",
        ],
    ),
    CategoryDef(
        slug="sustainability",
        keywords=[
            "saf", "sustainable aviation fuel", "emissions", "carbon", "net zero",
            "sustainability", "green", "climate", "corsia", "offset", "hydrogen",
            "electric aircraft", "biofuel", "decarbon", "environmental", "noise",
        ],
    ),
    CategoryDef(
        slug="airport",
        keywords=[
            "airport", "terminal", "runway", "expansion", "slot",
            "hub airport", "gate", "concourse", "apron", "baggage handling",
            "airport capacity", "new terminal", "airport opens", "ground handling",
            "security checkpoint", "customs", "passenger experience", "lounge",
        ],
    ),
    CategoryDef(
        slug="labor",
        keywords=[
            "union", "strike", "pilots", "contract negotiation", "staffing",
            "cabin crew", "flight attendant", "walkout", "industrial action", "pay deal",
            "labour", "labor", "workforce", "hiring", "layoff", "job cuts", "recruitment",
            "collective agreement", "shortage", "wage",
        ],
    ),
    CategoryDef(
        slug="events",
        keywords=[
            "conference", "summit", "air show", "airshow", "expo", "forum", "exhibition",
            "agm", "iata agm", "farnborough", "paris air show", "dubai airshow",
            "routes world", "world aviation festival", "aix", "apex", "mro europe",
            "trade show", "convention", "symposium", "congress", "aviation week event",
            "keynote", "delegates", "exhibitors", "singapore airshow",
        ],
        subcategories=[
            # "general" / "regional" aren't keyword-detected -- an events article
            # is "regional" whenever a region is detected via detect_region(),
            # otherwise it's "general". See app/llm/heuristic.py subcategorize().
            SubcategoryDef("general", []),
            SubcategoryDef("regional", []),
        ],
    ),
]

# The user's named main rivals (IATA codes) -- powers the newspaper's
# "Ana Rakipler" filter (airline=RIVALS matches any of these). TK is the home
# carrier and deliberately not in this list.
RIVAL_CODES: tuple[str, ...] = ("AF", "BA", "EK", "EY", "KL", "LH", "PC", "QR", "VF")

# Editorial weighting: how much this portal cares about a category, on the same
# 0-1 scale as ArticleEnrichment.importance_score. Raw importance is
# `confidence * 0.7 + min(corroborating_count, 5) * 0.06`, so it measures how
# *well-attested* a story is, not how much an RM desk needs it -- a Boeing order
# carried by ten wires outscores a single-sourced competitor fare move every
# time. This bonus buys back the beats the portal exists for.
#
# Two consumers, deliberately one definition (app/services/edition_service.py
# ranks the daily edition's front page by importance + bonus; the Gazete's
# `min_importance` filter in app/repositories/article_repository.py applies the
# floor to the same weighted sum). They have to agree, and a second copy of
# these numbers would drift on the first tuning pass. Lives here because
# taxonomy.py is a leaf module -- it imports nothing from the app, so both the
# service and the repository layer can pull it in without a cycle.
FOCUS_BONUS: dict[str, float] = {
    "revenue_management": 0.30,
    "network": 0.18,
    "finance": 0.10,
    "events": 0.08,
}

# "general" is the fallback category: whatever scores zero against every
# category above lands here. It has no keyword list or subcategories of its own.
GENERAL_CATEGORY = "general"
CATEGORY_SLUGS: list[str] = [c.slug for c in CATEGORIES] + [GENERAL_CATEGORY]

# Turkish display labels. Canonical: the newsletter, the newspaper sections, the
# recommendation prose and the frontend all read these rather than keeping their
# own copy. test_taxonomy_labels.py asserts the coverage stays complete.
CATEGORY_LABELS_TR: dict[str, str] = {
    "revenue_management": "Gelir Yönetimi",
    "fleet": "Filo",
    "network": "Ağ & Rota",
    "finance": "Finans",
    "safety": "Emniyet",
    "regulatory": "Regülasyon",
    "sustainability": "Sürdürülebilirlik",
    "airport": "Havalimanı",
    "labor": "İşgücü",
    "events": "Etkinlik",
    "general": "Genel",
}

# Region slugs are produced by COUNTRY_TO_REGION below; these are their names.
REGION_LABELS_TR: dict[str, str] = {
    "europe": "Avrupa",
    "middle-east": "Orta Doğu",
    "africa": "Afrika",
    "north-america": "Kuzey Amerika",
    "south-america": "Güney Amerika",
    "central-america": "Orta Amerika",
    "asia": "Asya",
    "southeast-asia": "Güneydoğu Asya",
    "oceania": "Okyanusya",
}

CATEGORY_KEYWORDS: dict[str, list[str]] = {c.slug: c.keywords for c in CATEGORIES}
SUBCATEGORY_KEYWORDS: dict[str, dict[str, list[str]]] = {
    c.slug: {s.slug: s.keywords for s in c.subcategories} for c in CATEGORIES if c.subcategories
}

# Country (as extracted by the entity gazetteer, see app/llm/gazetteer.py) ->
# world region slug. Mirrors frontend/src/lib/nav.ts `worldRegions`. This is a
# practical approximation, not an authoritative geopolitical grouping --
# e.g. Turkey is grouped with Middle East here to match how airline
# revenue-management teams typically benchmark it against Gulf carriers. That
# same call is now made in exactly one place: app/hubs.py used to file IST and
# SAW under "europe" while this table filed Turkey under "middle-east", so the
# Hub Explorer and the newspaper's region filter disagreed about the home hub.
# hubs.py follows this table.
#
# These are the assignments the product made by hand, kept verbatim: full
# coverage is layered *underneath* them from the generated country table below,
# so widening coverage can never silently reclassify a country the product
# already had an opinion about.
CURATED_COUNTRY_REGION: dict[str, str] = {
    "united kingdom": "europe", "france": "europe", "germany": "europe",
    "spain": "europe", "italy": "europe", "netherlands": "europe",
    "russia": "europe", "greece": "europe", "portugal": "europe",
    "switzerland": "europe", "austria": "europe", "belgium": "europe",
    "poland": "europe", "sweden": "europe", "norway": "europe",
    "denmark": "europe", "finland": "europe", "ireland": "europe",
    "iceland": "europe",
    "turkey": "middle-east", "qatar": "middle-east", "united arab emirates": "middle-east",
    "saudi arabia": "middle-east", "israel": "middle-east",
    "egypt": "africa", "south africa": "africa", "nigeria": "africa",
    "kenya": "africa", "morocco": "africa",
    "united states": "north-america", "canada": "north-america",
    "mexico": "central-america", "panama": "central-america", "costa rica": "central-america",
    "brazil": "south-america", "argentina": "south-america", "chile": "south-america",
    "colombia": "south-america", "peru": "south-america", "ecuador": "south-america",
    "china": "asia", "japan": "asia", "south korea": "asia", "india": "asia",
    "indonesia": "southeast-asia", "thailand": "southeast-asia", "vietnam": "southeast-asia",
    "philippines": "southeast-asia", "singapore": "southeast-asia",
    "australia": "oceania", "new zealand": "oceania",
}

# The other ~200 countries, generated from the OurAirports country list by
# scripts/build_airports.py and cross-checked against
# frontend/src/lib/geo/region-countries.ts (the map's own country -> region
# table) so a signal cannot land in one region on the map and another in the
# ledger. The old 47-entry table was the reason "Riyadh-Malaga" and "Bergen"
# resolved to no region at all: the airport fallback in
# app/llm/heuristic.detect_region had nothing to look the country up in.
COUNTRY_TO_REGION: dict[str, str] = {
    **country_regions_by_name(),
    **CURATED_COUNTRY_REGION,
}

# ---------------------------------------------------------------------------
# Risk Radarı taxonomy
#
# A closed set of 9 event types in 2 families, classified out of the *existing*
# news feed by the enrichment pipeline -- there is no separate disaster data
# source. Deliberately closed: an open-ended "what kind of disaster is this"
# field would drift into dozens of near-synonyms across re-enrichment runs and
# make the country rollup uncountable. Anything that doesn't fit one of these
# nine is not a risk event as far as this product is concerned, and stays null.
#
# The frontend (frontend/src/components/risk-radar-client.tsx) mirrors these
# slugs with the same Turkish labels and its own icon per type -- keep both
# sides in sync when the taxonomy changes.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class RiskTypeDef:
    slug: str
    family: str  # natural | conflict
    label_tr: str


RISK_FAMILIES: tuple[str, ...] = ("natural", "conflict")

RISK_TYPES: list[RiskTypeDef] = [
    RiskTypeDef("earthquake", "natural", "Deprem"),
    RiskTypeDef("flood", "natural", "Sel"),
    RiskTypeDef("wildfire", "natural", "Yangın"),
    RiskTypeDef("volcano", "natural", "Volkanik"),
    RiskTypeDef("storm", "natural", "Fırtına"),
    RiskTypeDef("war", "conflict", "Savaş/Çatışma"),
    RiskTypeDef("coup", "conflict", "Darbe"),
    RiskTypeDef("attack", "conflict", "Saldırı"),
    RiskTypeDef("unrest", "conflict", "Toplumsal Gerginlik"),
]

RISK_TYPE_SLUGS: tuple[str, ...] = tuple(r.slug for r in RISK_TYPES)
RISK_TYPE_FAMILY: dict[str, str] = {r.slug: r.family for r in RISK_TYPES}
RISK_TYPE_LABELS_TR: dict[str, str] = {r.slug: r.label_tr for r in RISK_TYPES}

# Reuses the app's existing high|medium|low convention (event impact_level,
# recommendation priority) rather than inventing a fourth severity vocabulary.
RISK_SEVERITIES: tuple[str, ...] = ("high", "medium", "low")

# Weighted score behind the "Sıcak Noktalar" ranking. Computed server-side (see
# app/api/v1/risks.py) so the map, the ranking and the list all order countries
# by the same number instead of three client-side re-derivations of it.
RISK_SEVERITY_WEIGHT: dict[str, int] = {"high": 3, "medium": 2, "low": 1}


def is_valid_risk_type(slug: str | None) -> bool:
    """Closed-set gate. Everything that writes risk_type -- the LLM path, the
    heuristic, the CLI backfill -- goes through this, so a model inventing
    "tsunami" or "hurricane" writes null rather than a slug nothing can render.
    """
    return slug in RISK_TYPE_SLUGS


def risk_family_of(slug: str | None) -> str | None:
    return RISK_TYPE_FAMILY.get(slug) if slug else None


# ---------------------------------------------------------------------------
# Risk Radarı taxonomy — v2 (Faz 7)
#
# A second, independent taxonomy alongside the one above. Deliberately not a
# replacement in place: `RISK_TYPES` and `is_valid_risk_type` are still what
# app/llm/heuristic.py's classify_risk_heuristic (the only risk classifier
# actually running in production today) reads and writes, and that keyword
# matcher's patterns are built for natural-disaster/conflict granularity
# (earthquake vs. flood vs. wildfire). Repointing those constants to this
# taxonomy would silently change what the live Risk Radar shows before v2 has
# been compared against v1 for a single day. The pipeline v2 runner
# (app/agents/runner.py) and the consolidated classifier (app/llm/classify.py)
# import from here instead; v1 never sees this section.
#
# The reorganisation itself is the owner's: a revenue-management desk does not
# file "fuel price spike" and "earthquake" as siblings under a generic
# "disaster" umbrella. Eight families group risk by what kind of business
# decision it should trigger -- geopolitical and operational read close to the
# old natural/conflict split, but economic, fuel-cost, market-competitive,
# demand and infrastructure have no equivalent in the old scheme at all, and
# are exactly the categories a fare-and-network desk actually watches for.
#
# Two leaf types per family: specific enough to be different events, closed
# enough that the country/family rollups stay countable. A model inventing a
# type outside this set fails the call (see llm/classify.py) rather than
# writing a slug nothing can render.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class RiskCategoryDef:
    slug: str
    family: str
    label_tr: str


RISK_CATEGORY_FAMILIES: tuple[str, ...] = (
    "geopolitical", "operational", "regulatory", "economic",
    "fuel_cost", "market_competitive", "demand", "infrastructure",
)

RISK_CATEGORY_FAMILY_LABELS_TR: dict[str, str] = {
    "geopolitical": "Jeopolitik",
    "operational": "Operasyonel",
    "regulatory": "Düzenleyici",
    "economic": "Ekonomik",
    "fuel_cost": "Yakıt-Maliyet",
    "market_competitive": "Pazar-Rekabet",
    "demand": "Talep",
    "infrastructure": "Altyapı",
}

RISK_CATEGORIES: list[RiskCategoryDef] = [
    # Geopolitical -- war, unrest and attacks were three separate types before;
    # a revenue desk reacts to all three the same way (route suspension,
    # insurance, crew safety), so they are one type here. Sanctions are their
    # own because the reaction is different (payment/clearing risk, not
    # operational risk).
    RiskCategoryDef("conflict", "geopolitical", "Çatışma"),
    RiskCategoryDef("sanctions", "geopolitical", "Yaptırım"),
    # Operational -- an accident/incident (the old "storm" grounding a
    # weather-named fighter jet lived here by keyword accident; it no longer
    # can, since this taxonomy has no bare weather types to collide with) vs.
    # a disruption that stops flights without anyone being hurt (strike,
    # closure, ATC action affecting one carrier).
    RiskCategoryDef("accident_incident", "operational", "Kaza/Olay"),
    RiskCategoryDef("disruption", "operational", "Operasyonel Aksama"),
    # Regulatory
    RiskCategoryDef("restriction", "regulatory", "Kısıtlama/Yasak"),
    RiskCategoryDef("policy_change", "regulatory", "Mevzuat Değişikliği"),
    # Economic
    RiskCategoryDef("currency_crisis", "economic", "Kur Krizi"),
    RiskCategoryDef("macro_shock", "economic", "Makroekonomik Şok"),
    # Fuel / cost
    RiskCategoryDef("fuel_price_spike", "fuel_cost", "Yakıt Fiyat Artışı"),
    RiskCategoryDef("fuel_shortage", "fuel_cost", "Yakıt Kıtlığı"),
    # Market / competitive
    RiskCategoryDef("capacity_shift", "market_competitive", "Kapasite Değişimi"),
    RiskCategoryDef("price_war", "market_competitive", "Fiyat Savaşı"),
    # Demand
    RiskCategoryDef("demand_shock", "demand", "Talep Düşüşü"),
    RiskCategoryDef("demand_surge", "demand", "Talep Artışı"),
    # Infrastructure -- an airport-side problem (closure, damage, congestion)
    # vs. an airspace/ATC-side one (a country closing its airspace, a control
    # centre outage) are different mitigations (reroute a station vs. reroute
    # a flight path), so they stay separate types.
    RiskCategoryDef("airport_disruption", "infrastructure", "Havalimanı Aksaması"),
    RiskCategoryDef("atc_disruption", "infrastructure", "Hava Trafik Aksaması"),
]

RISK_CATEGORY_SLUGS: tuple[str, ...] = tuple(r.slug for r in RISK_CATEGORIES)
RISK_CATEGORY_FAMILY_OF: dict[str, str] = {r.slug: r.family for r in RISK_CATEGORIES}
RISK_CATEGORY_LABELS_TR: dict[str, str] = {r.slug: r.label_tr for r in RISK_CATEGORIES}


def is_valid_risk_category(slug: str | None) -> bool:
    return slug in RISK_CATEGORY_SLUGS


def risk_category_family_of(slug: str | None) -> str | None:
    return RISK_CATEGORY_FAMILY_OF.get(slug) if slug else None
