// Generated by backend/scripts/export_taxonomy.py -- do not edit by hand.
//
// Run `python -m scripts.export_taxonomy` from backend/ after changing
// app/taxonomy.py. CI fails when this file is out of date, so the two sides
// cannot drift apart silently the way they used to.
//
// Only structural truth lives here. Turkish category labels, colors and icons
// are frontend concerns and stay in taxonomy.ts.

export type CategorySlug =
  | "revenue_management"
  | "fleet"
  | "network"
  | "finance"
  | "safety"
  | "regulatory"
  | "sustainability"
  | "airport"
  | "labor"
  | "events"
  | "general";

export const CATEGORY_SLUGS: readonly CategorySlug[] = ["revenue_management", "fleet", "network", "finance", "safety", "regulatory", "sustainability", "airport", "labor", "events", "general"] as const;


/** Turkish labels, owned by the backend -- the newsletter and PDF
 *  render these same strings. */
export const CATEGORY_LABELS_TR: Record<CategorySlug, string> = {
  "revenue_management": "Gelir Yönetimi",
  "fleet": "Filo",
  "network": "Ağ & Rota",
  "finance": "Finans",
  "safety": "Emniyet",
  "regulatory": "Regülasyon",
  "sustainability": "Sürdürülebilirlik",
  "airport": "Havalimanı",
  "labor": "İşgücü",
  "events": "Etkinlik",
  "general": "Genel",
};

export type SubcategorySlug =
  | "ancillary"
  | "cancellation"
  | "competitor"
  | "demand_capacity"
  | "distribution"
  | "equity"
  | "general"
  | "load_factor"
  | "maintenance"
  | "new_route"
  | "order_delivery"
  | "pricing"
  | "promotion"
  | "regional"
  | "results"
  | "seasonal";


/** Which subcategory slugs are legal under each category. */
export const SUBCATEGORIES_BY_CATEGORY: Record<
  CategorySlug,
  readonly SubcategorySlug[]
> = {
  "revenue_management": ["competitor", "pricing", "promotion", "demand_capacity", "load_factor", "ancillary", "distribution"],
  "fleet": ["order_delivery", "maintenance"],
  "network": ["new_route", "cancellation", "seasonal"],
  "finance": ["results", "equity"],
  "safety": [],
  "regulatory": [],
  "sustainability": [],
  "airport": [],
  "labor": [],
  "events": ["general", "regional"],
  "general": [],
};

export type RegionSlug =
  | "africa"
  | "asia"
  | "central-america"
  | "europe"
  | "middle-east"
  | "north-america"
  | "oceania"
  | "south-america"
  | "southeast-asia";

export const REGION_SLUGS: readonly RegionSlug[] = ["africa", "asia", "central-america", "europe", "middle-east", "north-america", "oceania", "south-america", "southeast-asia"] as const;


export const REGION_LABELS_TR: Record<RegionSlug, string> = {
  "africa": "Afrika",
  "asia": "Asya",
  "central-america": "Orta Amerika",
  "europe": "Avrupa",
  "middle-east": "Orta Doğu",
  "north-america": "Kuzey Amerika",
  "oceania": "Okyanusya",
  "south-america": "Güney Amerika",
  "southeast-asia": "Güneydoğu Asya",
};

export type RiskFamily =
  | "natural"
  | "conflict";

export type RiskSeverity =
  | "high"
  | "medium"
  | "low";

export type RiskTypeSlug =
  | "earthquake"
  | "flood"
  | "wildfire"
  | "volcano"
  | "storm"
  | "war"
  | "coup"
  | "attack"
  | "unrest";


export interface RiskTypeDef {
  slug: RiskTypeSlug;
  family: RiskFamily;
  /** Owned by the backend: the API returns these labels. */
  labelTr: string;
}

export const RISK_TYPES: readonly RiskTypeDef[] = [
  { slug: "earthquake", family: "natural", labelTr: "Deprem" },
  { slug: "flood", family: "natural", labelTr: "Sel" },
  { slug: "wildfire", family: "natural", labelTr: "Yangın" },
  { slug: "volcano", family: "natural", labelTr: "Volkanik" },
  { slug: "storm", family: "natural", labelTr: "Fırtına" },
  { slug: "war", family: "conflict", labelTr: "Savaş/Çatışma" },
  { slug: "coup", family: "conflict", labelTr: "Darbe" },
  { slug: "attack", family: "conflict", labelTr: "Saldırı" },
  { slug: "unrest", family: "conflict", labelTr: "Toplumsal Gerginlik" },
] as const;

export type RivalCode =
  | "AF"
  | "BA"
  | "EK"
  | "EY"
  | "KL"
  | "LH"
  | "PC"
  | "QR"
  | "VF";

export const RIVAL_CODES: readonly RivalCode[] = ["AF", "BA", "EK", "EY", "KL", "LH", "PC", "QR", "VF"] as const;
