// Generated by backend/scripts/export_taxonomy.py -- do not edit by hand.
//
// Run `python -m scripts.export_taxonomy` from backend/ after changing
// app/taxonomy.py. CI fails when this file is out of date, so the two sides
// cannot drift apart silently the way they used to.
//
// Only structural truth lives here. Turkish category labels, colors and icons
// are frontend concerns and stay in taxonomy.ts.

export type CategorySlug =
  | "revenue_management"
  | "fleet"
  | "network"
  | "finance"
  | "safety"
  | "regulatory"
  | "sustainability"
  | "airport"
  | "labor"
  | "events"
  | "general";

export const CATEGORY_SLUGS: readonly CategorySlug[] = ["revenue_management", "fleet", "network", "finance", "safety", "regulatory", "sustainability", "airport", "labor", "events", "general"] as const;


/** Turkish labels, owned by the backend -- the newsletter and PDF
 *  render these same strings. */
export const CATEGORY_LABELS_TR: Record<CategorySlug, string> = {
  "revenue_management": "Gelir Yönetimi",
  "fleet": "Filo",
  "network": "Ağ & Rota",
  "finance": "Finans",
  "safety": "Emniyet",
  "regulatory": "Regülasyon",
  "sustainability": "Sürdürülebilirlik",
  "airport": "Havalimanı",
  "labor": "İşgücü",
  "events": "Etkinlik",
  "general": "Genel",
};

export type SubcategorySlug =
  | "airport_capacity"
  | "ancillary"
  | "cancellation"
  | "capacity"
  | "competitor"
  | "demand"
  | "disruption"
  | "distribution"
  | "equity"
  | "forecasting"
  | "general"
  | "ground_handling"
  | "infrastructure"
  | "load_factor"
  | "maintenance"
  | "new_route"
  | "new_service"
  | "order_delivery"
  | "passenger_experience"
  | "pricing"
  | "promotion"
  | "regional"
  | "results"
  | "seasonal"
  | "slot"
  | "terminal"
  | "traffic";


/** Which subcategory slugs are legal under each category. */
export const SUBCATEGORIES_BY_CATEGORY: Record<
  CategorySlug,
  readonly SubcategorySlug[]
> = {
  "revenue_management": ["competitor", "pricing", "promotion", "demand", "capacity", "load_factor", "ancillary", "distribution", "forecasting"],
  "fleet": ["order_delivery", "maintenance"],
  "network": ["new_route", "cancellation", "seasonal"],
  "finance": ["results", "equity"],
  "safety": [],
  "regulatory": [],
  "sustainability": [],
  "airport": ["slot", "airport_capacity", "terminal", "infrastructure", "disruption", "traffic", "new_service", "ground_handling", "passenger_experience"],
  "labor": [],
  "events": ["general", "regional"],
  "general": [],
};

export type RegionSlug =
  | "africa"
  | "asia"
  | "central-america"
  | "europe"
  | "middle-east"
  | "north-america"
  | "oceania"
  | "south-america"
  | "southeast-asia";

export const REGION_SLUGS: readonly RegionSlug[] = ["africa", "asia", "central-america", "europe", "middle-east", "north-america", "oceania", "south-america", "southeast-asia"] as const;


export const REGION_LABELS_TR: Record<RegionSlug, string> = {
  "africa": "Afrika",
  "asia": "Asya",
  "central-america": "Orta Amerika",
  "europe": "Avrupa",
  "middle-east": "Orta Doğu",
  "north-america": "Kuzey Amerika",
  "oceania": "Okyanusya",
  "south-america": "Güney Amerika",
  "southeast-asia": "Güneydoğu Asya",
};

export type RiskFamily =
  | "natural"
  | "conflict";

export type RiskSeverity =
  | "high"
  | "medium"
  | "low";

export type RiskTypeSlug =
  | "earthquake"
  | "flood"
  | "wildfire"
  | "volcano"
  | "storm"
  | "war"
  | "coup"
  | "attack"
  | "unrest";


export interface RiskTypeDef {
  slug: RiskTypeSlug;
  family: RiskFamily;
  /** Owned by the backend: the API returns these labels. */
  labelTr: string;
}

export const RISK_TYPES: readonly RiskTypeDef[] = [
  { slug: "earthquake", family: "natural", labelTr: "Deprem" },
  { slug: "flood", family: "natural", labelTr: "Sel" },
  { slug: "wildfire", family: "natural", labelTr: "Yangın" },
  { slug: "volcano", family: "natural", labelTr: "Volkanik" },
  { slug: "storm", family: "natural", labelTr: "Fırtına" },
  { slug: "war", family: "conflict", labelTr: "Savaş/Çatışma" },
  { slug: "coup", family: "conflict", labelTr: "Darbe" },
  { slug: "attack", family: "conflict", labelTr: "Saldırı" },
  { slug: "unrest", family: "conflict", labelTr: "Toplumsal Gerginlik" },
] as const;

/** Every carrier the pipeline can attribute a campaign to. */
export type CarrierCode =
  | "AF"
  | "BA"
  | "EK"
  | "EY"
  | "KL"
  | "LH"
  | "QR"
  | "SQ"
  | "PC"
  | "VF"
  | "TK";

export const CARRIER_CODES: readonly CarrierCode[] = ["AF", "BA", "EK", "EY", "KL", "LH", "QR", "SQ", "PC", "VF", "TK"] as const;


export const CARRIER_NAMES: Record<CarrierCode, string> = {
  "AF": "Air France",
  "BA": "British Airways",
  "EK": "Emirates",
  "EY": "Etihad Airways",
  "KL": "KLM",
  "LH": "Lufthansa",
  "QR": "Qatar Airways",
  "SQ": "Singapore Airlines",
  "PC": "Pegasus Airlines",
  "VF": "AJet",
  "TK": "Turkish Airlines",
};

export type RivalCode =
  | "AF"
  | "BA"
  | "EK"
  | "EY"
  | "KL"
  | "LH"
  | "PC"
  | "QR"
  | "VF";

export const RIVAL_CODES: readonly RivalCode[] = ["AF", "BA", "EK", "EY", "KL", "LH", "PC", "QR", "VF"] as const;


/** Kampanya İstihbaratı -- see backend/app/taxonomy.py. */
export type CampaignType =
  | "FARE_DISCOUNT"
  | "PERCENT_DISCOUNT"
  | "FIXED_FARE"
  | "FLASH_SALE"
  | "EARLY_BOOKING"
  | "LAST_MINUTE"
  | "ROUND_TRIP_PROMOTION"
  | "ONE_WAY_PROMOTION"
  | "DESTINATION_PROMOTION"
  | "SEASONAL_PROMOTION"
  | "NEW_ROUTE_PROMOTION"
  | "BLACK_FRIDAY"
  | "CYBER_MONDAY"
  | "SUMMER_SALE"
  | "WINTER_SALE"
  | "RAMADAN_PROMOTION"
  | "EID_PROMOTION"
  | "NATIONAL_HOLIDAY"
  | "STUDENT_PROMOTION"
  | "FAMILY_PROMOTION"
  | "CORPORATE_PROMOTION"
  | "LOYALTY_PROMOTION"
  | "MILES_PROMOTION"
  | "BAGGAGE_PROMOTION"
  | "ANCILLARY_PROMOTION"
  | "PARTNER_PROMOTION"
  | "OTHER";

export const CAMPAIGN_TYPES: readonly CampaignType[] = ["FARE_DISCOUNT", "PERCENT_DISCOUNT", "FIXED_FARE", "FLASH_SALE", "EARLY_BOOKING", "LAST_MINUTE", "ROUND_TRIP_PROMOTION", "ONE_WAY_PROMOTION", "DESTINATION_PROMOTION", "SEASONAL_PROMOTION", "NEW_ROUTE_PROMOTION", "BLACK_FRIDAY", "CYBER_MONDAY", "SUMMER_SALE", "WINTER_SALE", "RAMADAN_PROMOTION", "EID_PROMOTION", "NATIONAL_HOLIDAY", "STUDENT_PROMOTION", "FAMILY_PROMOTION", "CORPORATE_PROMOTION", "LOYALTY_PROMOTION", "MILES_PROMOTION", "BAGGAGE_PROMOTION", "ANCILLARY_PROMOTION", "PARTNER_PROMOTION", "OTHER"] as const;


export const CAMPAIGN_TYPE_LABELS_TR: Record<CampaignType, string> = {
  "FARE_DISCOUNT": "Bilet İndirimi",
  "PERCENT_DISCOUNT": "Yüzde İndirim",
  "FIXED_FARE": "Sabit Fiyat",
  "FLASH_SALE": "Flaş İndirim",
  "EARLY_BOOKING": "Erken Rezervasyon",
  "LAST_MINUTE": "Son Dakika",
  "ROUND_TRIP_PROMOTION": "Gidiş-Dönüş Kampanyası",
  "ONE_WAY_PROMOTION": "Tek Yön Kampanyası",
  "DESTINATION_PROMOTION": "Destinasyon Kampanyası",
  "SEASONAL_PROMOTION": "Sezonluk Kampanya",
  "NEW_ROUTE_PROMOTION": "Yeni Hat Kampanyası",
  "BLACK_FRIDAY": "Black Friday",
  "CYBER_MONDAY": "Cyber Monday",
  "SUMMER_SALE": "Yaz İndirimi",
  "WINTER_SALE": "Kış İndirimi",
  "RAMADAN_PROMOTION": "Ramazan Kampanyası",
  "EID_PROMOTION": "Bayram Kampanyası",
  "NATIONAL_HOLIDAY": "Resmî Tatil Kampanyası",
  "STUDENT_PROMOTION": "Öğrenci Kampanyası",
  "FAMILY_PROMOTION": "Aile Kampanyası",
  "CORPORATE_PROMOTION": "Kurumsal Kampanya",
  "LOYALTY_PROMOTION": "Sadakat Programı Kampanyası",
  "MILES_PROMOTION": "Mil Kampanyası",
  "BAGGAGE_PROMOTION": "Bagaj Kampanyası",
  "ANCILLARY_PROMOTION": "Ek Hizmet Kampanyası",
  "PARTNER_PROMOTION": "İş Birliği Kampanyası",
  "OTHER": "Diğer",
};

export type CampaignBusinessClass =
  | "ACTIVE_CAMPAIGN"
  | "UPCOMING_CAMPAIGN"
  | "EXPIRED_CAMPAIGN"
  | "EVERGREEN_OFFER"
  | "NEWS_ONLY"
  | "PRODUCT_PROMOTION"
  | "LOYALTY_PROMOTION";

export const CAMPAIGN_BUSINESS_CLASSES: readonly CampaignBusinessClass[] = ["ACTIVE_CAMPAIGN", "UPCOMING_CAMPAIGN", "EXPIRED_CAMPAIGN", "EVERGREEN_OFFER", "NEWS_ONLY", "PRODUCT_PROMOTION", "LOYALTY_PROMOTION"] as const;


export const CAMPAIGN_BUSINESS_CLASS_LABELS_TR: Record<CampaignBusinessClass, string> = {
  "ACTIVE_CAMPAIGN": "Aktif Kampanya",
  "UPCOMING_CAMPAIGN": "Yaklaşan Kampanya",
  "EXPIRED_CAMPAIGN": "Süresi Dolmuş Kampanya",
  "EVERGREEN_OFFER": "Sürekli Teklif",
  "NEWS_ONLY": "Sadece Haber",
  "PRODUCT_PROMOTION": "Ürün/Hizmet Kampanyası",
  "LOYALTY_PROMOTION": "Sadakat Kampanyası",
};

export type CampaignKind =
  | "CAMPAIGN"
  | "PROMOTION";

export const CAMPAIGN_KINDS: readonly CampaignKind[] = ["CAMPAIGN", "PROMOTION"] as const;


export const CAMPAIGN_KIND_LABELS_TR: Record<CampaignKind, string> = {
  "CAMPAIGN": "Kampanya (fiyat)",
  "PROMOTION": "Promosyon (mekanizma)",
};

export type RouteScope =
  | "OND"
  | "CITY_PAIR"
  | "COUNTRY"
  | "REGION"
  | "NETWORK_WIDE";

export const ROUTE_SCOPES: readonly RouteScope[] = ["OND", "CITY_PAIR", "COUNTRY", "REGION", "NETWORK_WIDE"] as const;


export const ROUTE_SCOPE_LABELS_TR: Record<RouteScope, string> = {
  "OND": "Kalkış-Varış (OND)",
  "CITY_PAIR": "Şehir Çifti",
  "COUNTRY": "Ülke",
  "REGION": "Bölge",
  "NETWORK_WIDE": "Tüm Ağ",
};

export type CampaignStatus =
  | "UPCOMING"
  | "ACTIVE_BOOKING"
  | "BOOKING_CLOSED_TRAVEL_ACTIVE"
  | "EXPIRED"
  | "UNKNOWN";

export const CAMPAIGN_STATUSES: readonly CampaignStatus[] = ["UPCOMING", "ACTIVE_BOOKING", "BOOKING_CLOSED_TRAVEL_ACTIVE", "EXPIRED", "UNKNOWN"] as const;


export const CAMPAIGN_STATUS_LABELS_TR: Record<CampaignStatus, string> = {
  "UPCOMING": "Yakında",
  "ACTIVE_BOOKING": "Satışta",
  "BOOKING_CLOSED_TRAVEL_ACTIVE": "Satış kapandı, seyahat sürüyor",
  "EXPIRED": "Süresi doldu",
  "UNKNOWN": "Belirsiz",
};

export type PeriodKind =
  | "actual"
  | "estimate"
  | "forecast";

export const PERIOD_KINDS: readonly PeriodKind[] = ["actual", "estimate", "forecast"] as const;


export const PERIOD_KIND_LABELS_TR: Record<PeriodKind, string> = {
  "actual": "gerçekleşme",
  "estimate": "tahmini gerçekleşme",
  "forecast": "tahmin",
};
